from atlas.paths.api_atlas_v2_federation_settings_federation_settings_id_connected_org_configs_org_id.get import ApiForget
from atlas.paths.api_atlas_v2_federation_settings_federation_settings_id_connected_org_configs_org_id.delete import ApiFordelete
from atlas.paths.api_atlas_v2_federation_settings_federation_settings_id_connected_org_configs_org_id.patch import ApiForpatch


class ApiAtlasV2FederationSettingsFederationSettingsIdConnectedOrgConfigsOrgId(
    ApiForget,
    ApiFordelete,
    ApiForpatch,
):
    pass
