from atlas.paths.api_atlas_v2_groups_group_id_private_endpoint_cloud_provider_endpoint_service_endpoint_service_id.get import ApiForget
from atlas.paths.api_atlas_v2_groups_group_id_private_endpoint_cloud_provider_endpoint_service_endpoint_service_id.delete import ApiFordelete


class ApiAtlasV2GroupsGroupIdPrivateEndpointCloudProviderEndpointServiceEndpointServiceId(
    ApiForget,
    ApiFordelete,
):
    pass
