from atlas.paths.api_atlas_v2_groups_group_id_private_endpoint_serverless_instance_instance_name_endpoint_endpoint_id.get import ApiForget
from atlas.paths.api_atlas_v2_groups_group_id_private_endpoint_serverless_instance_instance_name_endpoint_endpoint_id.delete import ApiFordelete
from atlas.paths.api_atlas_v2_groups_group_id_private_endpoint_serverless_instance_instance_name_endpoint_endpoint_id.patch import ApiForpatch


class ApiAtlasV2GroupsGroupIdPrivateEndpointServerlessInstanceInstanceNameEndpointEndpointId(
    ApiForget,
    ApiFordelete,
    ApiForpatch,
):
    pass
