from atlas.paths.api_atlas_v2_federation_settings_federation_settings_id_identity_providers_identity_provider_id_metadata_xml.get import ApiForget


class ApiAtlasV2FederationSettingsFederationSettingsIdIdentityProvidersIdentityProviderIdMetadataXml(
    ApiForget,
):
    pass
