from atlas.paths.api_atlas_v2_groups_group_id_hosts_process_id_fts_metrics_indexes_database_name_collection_name_index_name_measurements.get import ApiForget


class ApiAtlasV2GroupsGroupIdHostsProcessIdFtsMetricsIndexesDatabaseNameCollectionNameIndexNameMeasurements(
    ApiForget,
):
    pass
