# coding: utf-8

"""
    MongoDB Atlas Administration API

    The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from atlas import schemas  # noqa: F401


class DLSIngestionSink(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Atlas Data Lake Storage as the destination for a Data Lake Pipeline.
    """


    class MetaOapg:
        
        class properties:
            
            
            class metadataProvider(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def AWS(cls):
                    return cls("AWS")
            metadataRegion = schemas.StrSchema
            
            
            class partitionFields(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['PartitionField']:
                        return PartitionField
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['PartitionField'], typing.List['PartitionField']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'partitionFields':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'PartitionField':
                    return super().__getitem__(i)
            
            
            class type(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def DLS(cls):
                    return cls("DLS")
            __annotations__ = {
                "metadataProvider": metadataProvider,
                "metadataRegion": metadataRegion,
                "partitionFields": partitionFields,
                "type": type,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metadataProvider"]) -> MetaOapg.properties.metadataProvider: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metadataRegion"]) -> MetaOapg.properties.metadataRegion: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["partitionFields"]) -> MetaOapg.properties.partitionFields: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["metadataProvider", "metadataRegion", "partitionFields", "type", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metadataProvider"]) -> typing.Union[MetaOapg.properties.metadataProvider, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metadataRegion"]) -> typing.Union[MetaOapg.properties.metadataRegion, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["partitionFields"]) -> typing.Union[MetaOapg.properties.partitionFields, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> typing.Union[MetaOapg.properties.type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["metadataProvider", "metadataRegion", "partitionFields", "type", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        metadataProvider: typing.Union[MetaOapg.properties.metadataProvider, str, schemas.Unset] = schemas.unset,
        metadataRegion: typing.Union[MetaOapg.properties.metadataRegion, str, schemas.Unset] = schemas.unset,
        partitionFields: typing.Union[MetaOapg.properties.partitionFields, list, tuple, schemas.Unset] = schemas.unset,
        type: typing.Union[MetaOapg.properties.type, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DLSIngestionSink':
        return super().__new__(
            cls,
            *_args,
            metadataProvider=metadataProvider,
            metadataRegion=metadataRegion,
            partitionFields=partitionFields,
            type=type,
            _configuration=_configuration,
            **kwargs,
        )

from atlas.model.partition_field import PartitionField
