# coding: utf-8

"""
    MongoDB Atlas Administration API

    The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from atlas import schemas  # noqa: F401


class FTSIndexAuditTypeView(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Unique identifier of event type.
    """


    class MetaOapg:
        enum_value_to_name = {
            "FTS_INDEX_DELETION_FAILED": "DELETION_FAILED",
            "FTS_INDEX_BUILD_COMPLETE": "BUILD_COMPLETE",
            "FTS_INDEX_BUILD_FAILED": "BUILD_FAILED",
            "FTS_INDEX_CREATED": "CREATED",
            "FTS_INDEX_UPDATED": "UPDATED",
            "FTS_INDEX_DELETED": "DELETED",
        }
    
    @schemas.classproperty
    def DELETION_FAILED(cls):
        return cls("FTS_INDEX_DELETION_FAILED")
    
    @schemas.classproperty
    def BUILD_COMPLETE(cls):
        return cls("FTS_INDEX_BUILD_COMPLETE")
    
    @schemas.classproperty
    def BUILD_FAILED(cls):
        return cls("FTS_INDEX_BUILD_FAILED")
    
    @schemas.classproperty
    def CREATED(cls):
        return cls("FTS_INDEX_CREATED")
    
    @schemas.classproperty
    def UPDATED(cls):
        return cls("FTS_INDEX_UPDATED")
    
    @schemas.classproperty
    def DELETED(cls):
        return cls("FTS_INDEX_DELETED")
