# coding: utf-8

"""
    MongoDB Atlas Administration API

    The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from atlas import schemas  # noqa: F401


class GCPProviderSettings(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "providerName",
        }
        
        class properties:
            providerName = schemas.StrSchema
        
            @staticmethod
            def autoScaling() -> typing.Type['GCPAutoScaling']:
                return GCPAutoScaling
            
            
            class instanceSizeName(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def M10(cls):
                    return cls("M10")
                
                @schemas.classproperty
                def M20(cls):
                    return cls("M20")
                
                @schemas.classproperty
                def M30(cls):
                    return cls("M30")
                
                @schemas.classproperty
                def M40(cls):
                    return cls("M40")
                
                @schemas.classproperty
                def M50(cls):
                    return cls("M50")
                
                @schemas.classproperty
                def M60(cls):
                    return cls("M60")
                
                @schemas.classproperty
                def M80(cls):
                    return cls("M80")
                
                @schemas.classproperty
                def M140(cls):
                    return cls("M140")
                
                @schemas.classproperty
                def M200(cls):
                    return cls("M200")
                
                @schemas.classproperty
                def M250(cls):
                    return cls("M250")
                
                @schemas.classproperty
                def M300(cls):
                    return cls("M300")
                
                @schemas.classproperty
                def M400(cls):
                    return cls("M400")
                
                @schemas.classproperty
                def R40(cls):
                    return cls("R40")
                
                @schemas.classproperty
                def R50(cls):
                    return cls("R50")
                
                @schemas.classproperty
                def R60(cls):
                    return cls("R60")
                
                @schemas.classproperty
                def R80(cls):
                    return cls("R80")
                
                @schemas.classproperty
                def R200(cls):
                    return cls("R200")
                
                @schemas.classproperty
                def R300(cls):
                    return cls("R300")
                
                @schemas.classproperty
                def R400(cls):
                    return cls("R400")
                
                @schemas.classproperty
                def R600(cls):
                    return cls("R600")
            
            
            class regionName(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def EASTERN_US(cls):
                    return cls("EASTERN_US")
                
                @schemas.classproperty
                def US_EAST_4(cls):
                    return cls("US_EAST_4")
                
                @schemas.classproperty
                def US_WEST_2(cls):
                    return cls("US_WEST_2")
                
                @schemas.classproperty
                def US_WEST_3(cls):
                    return cls("US_WEST_3")
                
                @schemas.classproperty
                def US_WEST_4(cls):
                    return cls("US_WEST_4")
                
                @schemas.classproperty
                def CENTRAL_US(cls):
                    return cls("CENTRAL_US")
                
                @schemas.classproperty
                def WESTERN_US(cls):
                    return cls("WESTERN_US")
                
                @schemas.classproperty
                def NORTH_AMERICA_NORTHEAST_1(cls):
                    return cls("NORTH_AMERICA_NORTHEAST_1")
                
                @schemas.classproperty
                def NORTH_AMERICA_NORTHEAST_2(cls):
                    return cls("NORTH_AMERICA_NORTHEAST_2")
                
                @schemas.classproperty
                def SOUTH_AMERICA_EAST_1(cls):
                    return cls("SOUTH_AMERICA_EAST_1")
                
                @schemas.classproperty
                def SOUTH_AMERICA_WEST_1(cls):
                    return cls("SOUTH_AMERICA_WEST_1")
                
                @schemas.classproperty
                def WESTERN_EUROPE(cls):
                    return cls("WESTERN_EUROPE")
                
                @schemas.classproperty
                def EUROPE_NORTH_1(cls):
                    return cls("EUROPE_NORTH_1")
                
                @schemas.classproperty
                def EUROPE_WEST_2(cls):
                    return cls("EUROPE_WEST_2")
                
                @schemas.classproperty
                def EUROPE_WEST_3(cls):
                    return cls("EUROPE_WEST_3")
                
                @schemas.classproperty
                def EUROPE_WEST_4(cls):
                    return cls("EUROPE_WEST_4")
                
                @schemas.classproperty
                def EUROPE_WEST_6(cls):
                    return cls("EUROPE_WEST_6")
                
                @schemas.classproperty
                def EUROPE_WEST_8(cls):
                    return cls("EUROPE_WEST_8")
                
                @schemas.classproperty
                def EUROPE_WEST_9(cls):
                    return cls("EUROPE_WEST_9")
                
                @schemas.classproperty
                def EUROPE_SOUTHWEST_1(cls):
                    return cls("EUROPE_SOUTHWEST_1")
                
                @schemas.classproperty
                def EUROPE_CENTRAL_2(cls):
                    return cls("EUROPE_CENTRAL_2")
                
                @schemas.classproperty
                def AUSTRALIA_SOUTHEAST_1(cls):
                    return cls("AUSTRALIA_SOUTHEAST_1")
                
                @schemas.classproperty
                def AUSTRALIA_SOUTHEAST_2(cls):
                    return cls("AUSTRALIA_SOUTHEAST_2")
                
                @schemas.classproperty
                def EASTERN_ASIA_PACIFIC(cls):
                    return cls("EASTERN_ASIA_PACIFIC")
                
                @schemas.classproperty
                def NORTHEASTERN_ASIA_PACIFIC(cls):
                    return cls("NORTHEASTERN_ASIA_PACIFIC")
                
                @schemas.classproperty
                def SOUTHEASTERN_ASIA_PACIFIC(cls):
                    return cls("SOUTHEASTERN_ASIA_PACIFIC")
                
                @schemas.classproperty
                def ASIA_EAST_2(cls):
                    return cls("ASIA_EAST_2")
                
                @schemas.classproperty
                def ASIA_NORTHEAST_2(cls):
                    return cls("ASIA_NORTHEAST_2")
                
                @schemas.classproperty
                def ASIA_NORTHEAST_3(cls):
                    return cls("ASIA_NORTHEAST_3")
                
                @schemas.classproperty
                def ASIA_SOUTH_1(cls):
                    return cls("ASIA_SOUTH_1")
                
                @schemas.classproperty
                def ASIA_SOUTH_2(cls):
                    return cls("ASIA_SOUTH_2")
                
                @schemas.classproperty
                def ASIA_SOUTHEAST_2(cls):
                    return cls("ASIA_SOUTHEAST_2")
            __annotations__ = {
                "providerName": providerName,
                "autoScaling": autoScaling,
                "instanceSizeName": instanceSizeName,
                "regionName": regionName,
            }
    
    providerName: MetaOapg.properties.providerName
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["providerName"]) -> MetaOapg.properties.providerName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["autoScaling"]) -> 'GCPAutoScaling': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["instanceSizeName"]) -> MetaOapg.properties.instanceSizeName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["regionName"]) -> MetaOapg.properties.regionName: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["providerName", "autoScaling", "instanceSizeName", "regionName", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["providerName"]) -> MetaOapg.properties.providerName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["autoScaling"]) -> typing.Union['GCPAutoScaling', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["instanceSizeName"]) -> typing.Union[MetaOapg.properties.instanceSizeName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["regionName"]) -> typing.Union[MetaOapg.properties.regionName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["providerName", "autoScaling", "instanceSizeName", "regionName", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        providerName: typing.Union[MetaOapg.properties.providerName, str, ],
        autoScaling: typing.Union['GCPAutoScaling', schemas.Unset] = schemas.unset,
        instanceSizeName: typing.Union[MetaOapg.properties.instanceSizeName, str, schemas.Unset] = schemas.unset,
        regionName: typing.Union[MetaOapg.properties.regionName, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'GCPProviderSettings':
        return super().__new__(
            cls,
            *_args,
            providerName=providerName,
            autoScaling=autoScaling,
            instanceSizeName=instanceSizeName,
            regionName=regionName,
            _configuration=_configuration,
            **kwargs,
        )

from atlas.model.gcp_auto_scaling import GCPAutoScaling
