import typing_extensions

from atlas.paths import PathValues
from atlas.apis.paths.api_atlas_v2 import ApiAtlasV2
from atlas.apis.paths.api_atlas_v2_alert_configs_matchers_field_names import ApiAtlasV2AlertConfigsMatchersFieldNames
from atlas.apis.paths.api_atlas_v2_clusters import ApiAtlasV2Clusters
from atlas.apis.paths.api_atlas_v2_example_info import ApiAtlasV2ExampleInfo
from atlas.apis.paths.api_atlas_v2_federation_settings_federation_settings_id import ApiAtlasV2FederationSettingsFederationSettingsId
from atlas.apis.paths.api_atlas_v2_federation_settings_federation_settings_id_connected_org_configs import ApiAtlasV2FederationSettingsFederationSettingsIdConnectedOrgConfigs
from atlas.apis.paths.api_atlas_v2_federation_settings_federation_settings_id_connected_org_configs_org_id import ApiAtlasV2FederationSettingsFederationSettingsIdConnectedOrgConfigsOrgId
from atlas.apis.paths.api_atlas_v2_federation_settings_federation_settings_id_connected_org_configs_org_id_role_mappings import ApiAtlasV2FederationSettingsFederationSettingsIdConnectedOrgConfigsOrgIdRoleMappings
from atlas.apis.paths.api_atlas_v2_federation_settings_federation_settings_id_connected_org_configs_org_id_role_mappings_id import ApiAtlasV2FederationSettingsFederationSettingsIdConnectedOrgConfigsOrgIdRoleMappingsId
from atlas.apis.paths.api_atlas_v2_federation_settings_federation_settings_id_identity_providers import ApiAtlasV2FederationSettingsFederationSettingsIdIdentityProviders
from atlas.apis.paths.api_atlas_v2_federation_settings_federation_settings_id_identity_providers_identity_provider_id import ApiAtlasV2FederationSettingsFederationSettingsIdIdentityProvidersIdentityProviderId
from atlas.apis.paths.api_atlas_v2_federation_settings_federation_settings_id_identity_providers_identity_provider_id_metadata_xml import ApiAtlasV2FederationSettingsFederationSettingsIdIdentityProvidersIdentityProviderIdMetadataXml
from atlas.apis.paths.api_atlas_v2_groups import ApiAtlasV2Groups
from atlas.apis.paths.api_atlas_v2_groups_by_name_group_name import ApiAtlasV2GroupsByNameGroupName
from atlas.apis.paths.api_atlas_v2_groups_group_id import ApiAtlasV2GroupsGroupId
from atlas.apis.paths.api_atlas_v2_groups_group_id_access_list import ApiAtlasV2GroupsGroupIdAccessList
from atlas.apis.paths.api_atlas_v2_groups_group_id_access_list_entry_value import ApiAtlasV2GroupsGroupIdAccessListEntryValue
from atlas.apis.paths.api_atlas_v2_groups_group_id_access_list_entry_value_status import ApiAtlasV2GroupsGroupIdAccessListEntryValueStatus
from atlas.apis.paths.api_atlas_v2_groups_group_id_alert_configs import ApiAtlasV2GroupsGroupIdAlertConfigs
from atlas.apis.paths.api_atlas_v2_groups_group_id_alert_configs_alert_config_id import ApiAtlasV2GroupsGroupIdAlertConfigsAlertConfigId
from atlas.apis.paths.api_atlas_v2_groups_group_id_alert_configs_alert_config_id_alerts import ApiAtlasV2GroupsGroupIdAlertConfigsAlertConfigIdAlerts
from atlas.apis.paths.api_atlas_v2_groups_group_id_alerts import ApiAtlasV2GroupsGroupIdAlerts
from atlas.apis.paths.api_atlas_v2_groups_group_id_alerts_alert_id import ApiAtlasV2GroupsGroupIdAlertsAlertId
from atlas.apis.paths.api_atlas_v2_groups_group_id_alerts_alert_id_alert_configs import ApiAtlasV2GroupsGroupIdAlertsAlertIdAlertConfigs
from atlas.apis.paths.api_atlas_v2_groups_group_id_api_keys import ApiAtlasV2GroupsGroupIdApiKeys
from atlas.apis.paths.api_atlas_v2_groups_group_id_api_keys_api_user_id import ApiAtlasV2GroupsGroupIdApiKeysApiUserId
from atlas.apis.paths.api_atlas_v2_groups_group_id_audit_log import ApiAtlasV2GroupsGroupIdAuditLog
from atlas.apis.paths.api_atlas_v2_groups_group_id_aws_custom_dns import ApiAtlasV2GroupsGroupIdAwsCustomDNS
from atlas.apis.paths.api_atlas_v2_groups_group_id_backup_export_buckets import ApiAtlasV2GroupsGroupIdBackupExportBuckets
from atlas.apis.paths.api_atlas_v2_groups_group_id_backup_export_buckets_export_bucket_id import ApiAtlasV2GroupsGroupIdBackupExportBucketsExportBucketId
from atlas.apis.paths.api_atlas_v2_groups_group_id_cloud_provider_access import ApiAtlasV2GroupsGroupIdCloudProviderAccess
from atlas.apis.paths.api_atlas_v2_groups_group_id_cloud_provider_access_cloud_provider_role_id import ApiAtlasV2GroupsGroupIdCloudProviderAccessCloudProviderRoleId
from atlas.apis.paths.api_atlas_v2_groups_group_id_cloud_provider_access_role_id import ApiAtlasV2GroupsGroupIdCloudProviderAccessRoleId
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters import ApiAtlasV2GroupsGroupIdClusters
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_provider_regions import ApiAtlasV2GroupsGroupIdClustersProviderRegions
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_tenant_upgrade import ApiAtlasV2GroupsGroupIdClustersTenantUpgrade
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_tenant_upgrade_to_serverless import ApiAtlasV2GroupsGroupIdClustersTenantUpgradeToServerless
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name import ApiAtlasV2GroupsGroupIdClustersClusterName
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_backup_exports import ApiAtlasV2GroupsGroupIdClustersClusterNameBackupExports
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_backup_exports_export_id import ApiAtlasV2GroupsGroupIdClustersClusterNameBackupExportsExportId
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_backup_restore_jobs import ApiAtlasV2GroupsGroupIdClustersClusterNameBackupRestoreJobs
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_backup_restore_jobs_restore_job_id import ApiAtlasV2GroupsGroupIdClustersClusterNameBackupRestoreJobsRestoreJobId
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_backup_schedule import ApiAtlasV2GroupsGroupIdClustersClusterNameBackupSchedule
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_backup_snapshots import ApiAtlasV2GroupsGroupIdClustersClusterNameBackupSnapshots
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_backup_snapshots_sharded_cluster_snapshot_id import ApiAtlasV2GroupsGroupIdClustersClusterNameBackupSnapshotsShardedClusterSnapshotId
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_backup_snapshots_sharded_clusters import ApiAtlasV2GroupsGroupIdClustersClusterNameBackupSnapshotsShardedClusters
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_backup_snapshots_snapshot_id import ApiAtlasV2GroupsGroupIdClustersClusterNameBackupSnapshotsSnapshotId
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_backup_tenant_download import ApiAtlasV2GroupsGroupIdClustersClusterNameBackupTenantDownload
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_backup_tenant_restore import ApiAtlasV2GroupsGroupIdClustersClusterNameBackupTenantRestore
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_backup_tenant_restores import ApiAtlasV2GroupsGroupIdClustersClusterNameBackupTenantRestores
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_backup_tenant_restores_restore_id import ApiAtlasV2GroupsGroupIdClustersClusterNameBackupTenantRestoresRestoreId
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_backup_tenant_snapshots import ApiAtlasV2GroupsGroupIdClustersClusterNameBackupTenantSnapshots
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_backup_tenant_snapshots_snapshot_id import ApiAtlasV2GroupsGroupIdClustersClusterNameBackupTenantSnapshotsSnapshotId
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_backup_checkpoints import ApiAtlasV2GroupsGroupIdClustersClusterNameBackupCheckpoints
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_backup_checkpoints_checkpoint_id import ApiAtlasV2GroupsGroupIdClustersClusterNameBackupCheckpointsCheckpointId
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_fts_indexes import ApiAtlasV2GroupsGroupIdClustersClusterNameFtsIndexes
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_fts_indexes_database_name_collection_name import ApiAtlasV2GroupsGroupIdClustersClusterNameFtsIndexesDatabaseNameCollectionName
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_fts_indexes_index_id import ApiAtlasV2GroupsGroupIdClustersClusterNameFtsIndexesIndexId
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_global_writes import ApiAtlasV2GroupsGroupIdClustersClusterNameGlobalWrites
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_global_writes_custom_zone_mapping import ApiAtlasV2GroupsGroupIdClustersClusterNameGlobalWritesCustomZoneMapping
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_global_writes_managed_namespaces import ApiAtlasV2GroupsGroupIdClustersClusterNameGlobalWritesManagedNamespaces
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_index import ApiAtlasV2GroupsGroupIdClustersClusterNameIndex
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_online_archives import ApiAtlasV2GroupsGroupIdClustersClusterNameOnlineArchives
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_online_archives_query_logs_gz import ApiAtlasV2GroupsGroupIdClustersClusterNameOnlineArchivesQueryLogsGz
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_online_archives_archive_id import ApiAtlasV2GroupsGroupIdClustersClusterNameOnlineArchivesArchiveId
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_outage_simulation import ApiAtlasV2GroupsGroupIdClustersClusterNameOutageSimulation
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_process_args import ApiAtlasV2GroupsGroupIdClustersClusterNameProcessArgs
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_restart_primaries import ApiAtlasV2GroupsGroupIdClustersClusterNameRestartPrimaries
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_restore_jobs import ApiAtlasV2GroupsGroupIdClustersClusterNameRestoreJobs
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_restore_jobs_job_id import ApiAtlasV2GroupsGroupIdClustersClusterNameRestoreJobsJobId
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_snapshot_schedule import ApiAtlasV2GroupsGroupIdClustersClusterNameSnapshotSchedule
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_snapshots import ApiAtlasV2GroupsGroupIdClustersClusterNameSnapshots
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_snapshots_snapshot_id import ApiAtlasV2GroupsGroupIdClustersClusterNameSnapshotsSnapshotId
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_cluster_name_status import ApiAtlasV2GroupsGroupIdClustersClusterNameStatus
from atlas.apis.paths.api_atlas_v2_groups_group_id_clusters_host_name_logs_log_name_gz import ApiAtlasV2GroupsGroupIdClustersHostNameLogsLogNameGz
from atlas.apis.paths.api_atlas_v2_groups_group_id_containers import ApiAtlasV2GroupsGroupIdContainers
from atlas.apis.paths.api_atlas_v2_groups_group_id_containers_all import ApiAtlasV2GroupsGroupIdContainersAll
from atlas.apis.paths.api_atlas_v2_groups_group_id_containers_container_id import ApiAtlasV2GroupsGroupIdContainersContainerId
from atlas.apis.paths.api_atlas_v2_groups_group_id_custom_db_roles_roles import ApiAtlasV2GroupsGroupIdCustomDBRolesRoles
from atlas.apis.paths.api_atlas_v2_groups_group_id_custom_db_roles_roles_role_name import ApiAtlasV2GroupsGroupIdCustomDBRolesRolesRoleName
from atlas.apis.paths.api_atlas_v2_groups_group_id_data_federation import ApiAtlasV2GroupsGroupIdDataFederation
from atlas.apis.paths.api_atlas_v2_groups_group_id_data_federation_tenant_name import ApiAtlasV2GroupsGroupIdDataFederationTenantName
from atlas.apis.paths.api_atlas_v2_groups_group_id_data_federation_tenant_name_limits import ApiAtlasV2GroupsGroupIdDataFederationTenantNameLimits
from atlas.apis.paths.api_atlas_v2_groups_group_id_data_federation_tenant_name_limits_limit_name import ApiAtlasV2GroupsGroupIdDataFederationTenantNameLimitsLimitName
from atlas.apis.paths.api_atlas_v2_groups_group_id_data_federation_tenant_name_query_logs_gz import ApiAtlasV2GroupsGroupIdDataFederationTenantNameQueryLogsGz
from atlas.apis.paths.api_atlas_v2_groups_group_id_data_protection import ApiAtlasV2GroupsGroupIdDataProtection
from atlas.apis.paths.api_atlas_v2_groups_group_id_database_users import ApiAtlasV2GroupsGroupIdDatabaseUsers
from atlas.apis.paths.api_atlas_v2_groups_group_id_database_users_database_name_username import ApiAtlasV2GroupsGroupIdDatabaseUsersDatabaseNameUsername
from atlas.apis.paths.api_atlas_v2_groups_group_id_database_users_username_certs import ApiAtlasV2GroupsGroupIdDatabaseUsersUsernameCerts
from atlas.apis.paths.api_atlas_v2_groups_group_id_db_access_history_clusters_cluster_name import ApiAtlasV2GroupsGroupIdDbAccessHistoryClustersClusterName
from atlas.apis.paths.api_atlas_v2_groups_group_id_db_access_history_processes_hostname import ApiAtlasV2GroupsGroupIdDbAccessHistoryProcessesHostname
from atlas.apis.paths.api_atlas_v2_groups_group_id_encryption_at_rest import ApiAtlasV2GroupsGroupIdEncryptionAtRest
from atlas.apis.paths.api_atlas_v2_groups_group_id_events import ApiAtlasV2GroupsGroupIdEvents
from atlas.apis.paths.api_atlas_v2_groups_group_id_events_event_id import ApiAtlasV2GroupsGroupIdEventsEventId
from atlas.apis.paths.api_atlas_v2_groups_group_id_hosts_process_id_fts_metrics import ApiAtlasV2GroupsGroupIdHostsProcessIdFtsMetrics
from atlas.apis.paths.api_atlas_v2_groups_group_id_hosts_process_id_fts_metrics_indexes_database_name_collection_name_measurements import ApiAtlasV2GroupsGroupIdHostsProcessIdFtsMetricsIndexesDatabaseNameCollectionNameMeasurements
from atlas.apis.paths.api_atlas_v2_groups_group_id_hosts_process_id_fts_metrics_indexes_database_name_collection_name_index_name_measurements import ApiAtlasV2GroupsGroupIdHostsProcessIdFtsMetricsIndexesDatabaseNameCollectionNameIndexNameMeasurements
from atlas.apis.paths.api_atlas_v2_groups_group_id_hosts_process_id_fts_metrics_measurements import ApiAtlasV2GroupsGroupIdHostsProcessIdFtsMetricsMeasurements
from atlas.apis.paths.api_atlas_v2_groups_group_id_integrations import ApiAtlasV2GroupsGroupIdIntegrations
from atlas.apis.paths.api_atlas_v2_groups_group_id_integrations_integration_type import ApiAtlasV2GroupsGroupIdIntegrationsIntegrationType
from atlas.apis.paths.api_atlas_v2_groups_group_id_invites import ApiAtlasV2GroupsGroupIdInvites
from atlas.apis.paths.api_atlas_v2_groups_group_id_invites_invitation_id import ApiAtlasV2GroupsGroupIdInvitesInvitationId
from atlas.apis.paths.api_atlas_v2_groups_group_id_limits import ApiAtlasV2GroupsGroupIdLimits
from atlas.apis.paths.api_atlas_v2_groups_group_id_limits_limit_name import ApiAtlasV2GroupsGroupIdLimitsLimitName
from atlas.apis.paths.api_atlas_v2_groups_group_id_live_migrations import ApiAtlasV2GroupsGroupIdLiveMigrations
from atlas.apis.paths.api_atlas_v2_groups_group_id_live_migrations_validate import ApiAtlasV2GroupsGroupIdLiveMigrationsValidate
from atlas.apis.paths.api_atlas_v2_groups_group_id_live_migrations_validate_validation_id import ApiAtlasV2GroupsGroupIdLiveMigrationsValidateValidationId
from atlas.apis.paths.api_atlas_v2_groups_group_id_live_migrations_live_migration_id import ApiAtlasV2GroupsGroupIdLiveMigrationsLiveMigrationId
from atlas.apis.paths.api_atlas_v2_groups_group_id_live_migrations_live_migration_id_cutover import ApiAtlasV2GroupsGroupIdLiveMigrationsLiveMigrationIdCutover
from atlas.apis.paths.api_atlas_v2_groups_group_id_maintenance_window import ApiAtlasV2GroupsGroupIdMaintenanceWindow
from atlas.apis.paths.api_atlas_v2_groups_group_id_maintenance_window_auto_defer import ApiAtlasV2GroupsGroupIdMaintenanceWindowAutoDefer
from atlas.apis.paths.api_atlas_v2_groups_group_id_maintenance_window_defer import ApiAtlasV2GroupsGroupIdMaintenanceWindowDefer
from atlas.apis.paths.api_atlas_v2_groups_group_id_managed_slow_ms_disable import ApiAtlasV2GroupsGroupIdManagedSlowMsDisable
from atlas.apis.paths.api_atlas_v2_groups_group_id_managed_slow_ms_enable import ApiAtlasV2GroupsGroupIdManagedSlowMsEnable
from atlas.apis.paths.api_atlas_v2_groups_group_id_peers import ApiAtlasV2GroupsGroupIdPeers
from atlas.apis.paths.api_atlas_v2_groups_group_id_peers_peer_id import ApiAtlasV2GroupsGroupIdPeersPeerId
from atlas.apis.paths.api_atlas_v2_groups_group_id_pipelines import ApiAtlasV2GroupsGroupIdPipelines
from atlas.apis.paths.api_atlas_v2_groups_group_id_pipelines_pipeline_name import ApiAtlasV2GroupsGroupIdPipelinesPipelineName
from atlas.apis.paths.api_atlas_v2_groups_group_id_pipelines_pipeline_name_available_schedules import ApiAtlasV2GroupsGroupIdPipelinesPipelineNameAvailableSchedules
from atlas.apis.paths.api_atlas_v2_groups_group_id_pipelines_pipeline_name_available_snapshots import ApiAtlasV2GroupsGroupIdPipelinesPipelineNameAvailableSnapshots
from atlas.apis.paths.api_atlas_v2_groups_group_id_pipelines_pipeline_name_pause import ApiAtlasV2GroupsGroupIdPipelinesPipelineNamePause
from atlas.apis.paths.api_atlas_v2_groups_group_id_pipelines_pipeline_name_resume import ApiAtlasV2GroupsGroupIdPipelinesPipelineNameResume
from atlas.apis.paths.api_atlas_v2_groups_group_id_pipelines_pipeline_name_runs import ApiAtlasV2GroupsGroupIdPipelinesPipelineNameRuns
from atlas.apis.paths.api_atlas_v2_groups_group_id_pipelines_pipeline_name_runs_pipeline_run_id import ApiAtlasV2GroupsGroupIdPipelinesPipelineNameRunsPipelineRunId
from atlas.apis.paths.api_atlas_v2_groups_group_id_pipelines_pipeline_name_trigger import ApiAtlasV2GroupsGroupIdPipelinesPipelineNameTrigger
from atlas.apis.paths.api_atlas_v2_groups_group_id_private_endpoint_endpoint_service import ApiAtlasV2GroupsGroupIdPrivateEndpointEndpointService
from atlas.apis.paths.api_atlas_v2_groups_group_id_private_endpoint_regional_mode import ApiAtlasV2GroupsGroupIdPrivateEndpointRegionalMode
from atlas.apis.paths.api_atlas_v2_groups_group_id_private_endpoint_serverless_instance_instance_name_endpoint import ApiAtlasV2GroupsGroupIdPrivateEndpointServerlessInstanceInstanceNameEndpoint
from atlas.apis.paths.api_atlas_v2_groups_group_id_private_endpoint_serverless_instance_instance_name_endpoint_endpoint_id import ApiAtlasV2GroupsGroupIdPrivateEndpointServerlessInstanceInstanceNameEndpointEndpointId
from atlas.apis.paths.api_atlas_v2_groups_group_id_private_endpoint_cloud_provider_endpoint_service import ApiAtlasV2GroupsGroupIdPrivateEndpointCloudProviderEndpointService
from atlas.apis.paths.api_atlas_v2_groups_group_id_private_endpoint_cloud_provider_endpoint_service_endpoint_service_id import ApiAtlasV2GroupsGroupIdPrivateEndpointCloudProviderEndpointServiceEndpointServiceId
from atlas.apis.paths.api_atlas_v2_groups_group_id_private_endpoint_cloud_provider_endpoint_service_endpoint_service_id_endpoint import ApiAtlasV2GroupsGroupIdPrivateEndpointCloudProviderEndpointServiceEndpointServiceIdEndpoint
from atlas.apis.paths.api_atlas_v2_groups_group_id_private_endpoint_cloud_provider_endpoint_service_endpoint_service_id_endpoint_endpoint_id import ApiAtlasV2GroupsGroupIdPrivateEndpointCloudProviderEndpointServiceEndpointServiceIdEndpointEndpointId
from atlas.apis.paths.api_atlas_v2_groups_group_id_private_ip_mode import ApiAtlasV2GroupsGroupIdPrivateIpMode
from atlas.apis.paths.api_atlas_v2_groups_group_id_private_network_settings_endpoint_ids import ApiAtlasV2GroupsGroupIdPrivateNetworkSettingsEndpointIds
from atlas.apis.paths.api_atlas_v2_groups_group_id_private_network_settings_endpoint_ids_endpoint_id import ApiAtlasV2GroupsGroupIdPrivateNetworkSettingsEndpointIdsEndpointId
from atlas.apis.paths.api_atlas_v2_groups_group_id_processes import ApiAtlasV2GroupsGroupIdProcesses
from atlas.apis.paths.api_atlas_v2_groups_group_id_processes_process_id import ApiAtlasV2GroupsGroupIdProcessesProcessId
from atlas.apis.paths.api_atlas_v2_groups_group_id_processes_process_id_databases import ApiAtlasV2GroupsGroupIdProcessesProcessIdDatabases
from atlas.apis.paths.api_atlas_v2_groups_group_id_processes_process_id_databases_database_name import ApiAtlasV2GroupsGroupIdProcessesProcessIdDatabasesDatabaseName
from atlas.apis.paths.api_atlas_v2_groups_group_id_processes_process_id_databases_database_name_measurements import ApiAtlasV2GroupsGroupIdProcessesProcessIdDatabasesDatabaseNameMeasurements
from atlas.apis.paths.api_atlas_v2_groups_group_id_processes_process_id_disks import ApiAtlasV2GroupsGroupIdProcessesProcessIdDisks
from atlas.apis.paths.api_atlas_v2_groups_group_id_processes_process_id_disks_partition_name import ApiAtlasV2GroupsGroupIdProcessesProcessIdDisksPartitionName
from atlas.apis.paths.api_atlas_v2_groups_group_id_processes_process_id_disks_partition_name_measurements import ApiAtlasV2GroupsGroupIdProcessesProcessIdDisksPartitionNameMeasurements
from atlas.apis.paths.api_atlas_v2_groups_group_id_processes_process_id_measurements import ApiAtlasV2GroupsGroupIdProcessesProcessIdMeasurements
from atlas.apis.paths.api_atlas_v2_groups_group_id_processes_process_id_performance_advisor_namespaces import ApiAtlasV2GroupsGroupIdProcessesProcessIdPerformanceAdvisorNamespaces
from atlas.apis.paths.api_atlas_v2_groups_group_id_processes_process_id_performance_advisor_slow_query_logs import ApiAtlasV2GroupsGroupIdProcessesProcessIdPerformanceAdvisorSlowQueryLogs
from atlas.apis.paths.api_atlas_v2_groups_group_id_processes_process_id_performance_advisor_suggested_indexes import ApiAtlasV2GroupsGroupIdProcessesProcessIdPerformanceAdvisorSuggestedIndexes
from atlas.apis.paths.api_atlas_v2_groups_group_id_sample_dataset_load_name import ApiAtlasV2GroupsGroupIdSampleDatasetLoadName
from atlas.apis.paths.api_atlas_v2_groups_group_id_sample_dataset_load_sample_dataset_id import ApiAtlasV2GroupsGroupIdSampleDatasetLoadSampleDatasetId
from atlas.apis.paths.api_atlas_v2_groups_group_id_serverless import ApiAtlasV2GroupsGroupIdServerless
from atlas.apis.paths.api_atlas_v2_groups_group_id_serverless_cluster_name_backup_restore_jobs import ApiAtlasV2GroupsGroupIdServerlessClusterNameBackupRestoreJobs
from atlas.apis.paths.api_atlas_v2_groups_group_id_serverless_cluster_name_backup_restore_jobs_restore_job_id import ApiAtlasV2GroupsGroupIdServerlessClusterNameBackupRestoreJobsRestoreJobId
from atlas.apis.paths.api_atlas_v2_groups_group_id_serverless_cluster_name_backup_snapshots import ApiAtlasV2GroupsGroupIdServerlessClusterNameBackupSnapshots
from atlas.apis.paths.api_atlas_v2_groups_group_id_serverless_cluster_name_backup_snapshots_snapshot_id import ApiAtlasV2GroupsGroupIdServerlessClusterNameBackupSnapshotsSnapshotId
from atlas.apis.paths.api_atlas_v2_groups_group_id_serverless_name import ApiAtlasV2GroupsGroupIdServerlessName
from atlas.apis.paths.api_atlas_v2_groups_group_id_settings import ApiAtlasV2GroupsGroupIdSettings
from atlas.apis.paths.api_atlas_v2_groups_group_id_teams import ApiAtlasV2GroupsGroupIdTeams
from atlas.apis.paths.api_atlas_v2_groups_group_id_teams_team_id import ApiAtlasV2GroupsGroupIdTeamsTeamId
from atlas.apis.paths.api_atlas_v2_groups_group_id_user_security import ApiAtlasV2GroupsGroupIdUserSecurity
from atlas.apis.paths.api_atlas_v2_groups_group_id_user_security_customer_x509 import ApiAtlasV2GroupsGroupIdUserSecurityCustomerX509
from atlas.apis.paths.api_atlas_v2_groups_group_id_user_security_ldap_user_to_dn_mapping import ApiAtlasV2GroupsGroupIdUserSecurityLdapUserToDNMapping
from atlas.apis.paths.api_atlas_v2_groups_group_id_user_security_ldap_verify import ApiAtlasV2GroupsGroupIdUserSecurityLdapVerify
from atlas.apis.paths.api_atlas_v2_groups_group_id_user_security_ldap_verify_request_id import ApiAtlasV2GroupsGroupIdUserSecurityLdapVerifyRequestId
from atlas.apis.paths.api_atlas_v2_groups_group_id_users import ApiAtlasV2GroupsGroupIdUsers
from atlas.apis.paths.api_atlas_v2_groups_group_id_users_user_id import ApiAtlasV2GroupsGroupIdUsersUserId
from atlas.apis.paths.api_atlas_v2_orgs import ApiAtlasV2Orgs
from atlas.apis.paths.api_atlas_v2_orgs_org_id import ApiAtlasV2OrgsOrgId
from atlas.apis.paths.api_atlas_v2_orgs_org_id_api_keys import ApiAtlasV2OrgsOrgIdApiKeys
from atlas.apis.paths.api_atlas_v2_orgs_org_id_api_keys_api_user_id import ApiAtlasV2OrgsOrgIdApiKeysApiUserId
from atlas.apis.paths.api_atlas_v2_orgs_org_id_api_keys_api_user_id_access_list import ApiAtlasV2OrgsOrgIdApiKeysApiUserIdAccessList
from atlas.apis.paths.api_atlas_v2_orgs_org_id_api_keys_api_user_id_access_list_ip_address import ApiAtlasV2OrgsOrgIdApiKeysApiUserIdAccessListIpAddress
from atlas.apis.paths.api_atlas_v2_orgs_org_id_events import ApiAtlasV2OrgsOrgIdEvents
from atlas.apis.paths.api_atlas_v2_orgs_org_id_events_event_id import ApiAtlasV2OrgsOrgIdEventsEventId
from atlas.apis.paths.api_atlas_v2_orgs_org_id_federation_settings import ApiAtlasV2OrgsOrgIdFederationSettings
from atlas.apis.paths.api_atlas_v2_orgs_org_id_groups import ApiAtlasV2OrgsOrgIdGroups
from atlas.apis.paths.api_atlas_v2_orgs_org_id_invites import ApiAtlasV2OrgsOrgIdInvites
from atlas.apis.paths.api_atlas_v2_orgs_org_id_invites_invitation_id import ApiAtlasV2OrgsOrgIdInvitesInvitationId
from atlas.apis.paths.api_atlas_v2_orgs_org_id_invoices import ApiAtlasV2OrgsOrgIdInvoices
from atlas.apis.paths.api_atlas_v2_orgs_org_id_invoices_pending import ApiAtlasV2OrgsOrgIdInvoicesPending
from atlas.apis.paths.api_atlas_v2_orgs_org_id_invoices_invoice_id import ApiAtlasV2OrgsOrgIdInvoicesInvoiceId
from atlas.apis.paths.api_atlas_v2_orgs_org_id_invoices_invoice_id_csv import ApiAtlasV2OrgsOrgIdInvoicesInvoiceIdCsv
from atlas.apis.paths.api_atlas_v2_orgs_org_id_live_migrations_available_projects import ApiAtlasV2OrgsOrgIdLiveMigrationsAvailableProjects
from atlas.apis.paths.api_atlas_v2_orgs_org_id_live_migrations_link_tokens import ApiAtlasV2OrgsOrgIdLiveMigrationsLinkTokens
from atlas.apis.paths.api_atlas_v2_orgs_org_id_settings import ApiAtlasV2OrgsOrgIdSettings
from atlas.apis.paths.api_atlas_v2_orgs_org_id_teams import ApiAtlasV2OrgsOrgIdTeams
from atlas.apis.paths.api_atlas_v2_orgs_org_id_teams_by_name_team_name import ApiAtlasV2OrgsOrgIdTeamsByNameTeamName
from atlas.apis.paths.api_atlas_v2_orgs_org_id_teams_team_id import ApiAtlasV2OrgsOrgIdTeamsTeamId
from atlas.apis.paths.api_atlas_v2_orgs_org_id_teams_team_id_users import ApiAtlasV2OrgsOrgIdTeamsTeamIdUsers
from atlas.apis.paths.api_atlas_v2_orgs_org_id_teams_team_id_users_user_id import ApiAtlasV2OrgsOrgIdTeamsTeamIdUsersUserId
from atlas.apis.paths.api_atlas_v2_orgs_org_id_users import ApiAtlasV2OrgsOrgIdUsers
from atlas.apis.paths.api_atlas_v2_users import ApiAtlasV2Users
from atlas.apis.paths.api_atlas_v2_users_by_name_user_name import ApiAtlasV2UsersByNameUserName
from atlas.apis.paths.api_atlas_v2_users_user_id import ApiAtlasV2UsersUserId

PathToApi = typing_extensions.TypedDict(
    'PathToApi',
    {
        PathValues.API_ATLAS_V2: ApiAtlasV2,
        PathValues.API_ATLAS_V2_ALERT_CONFIGS_MATCHERS_FIELD_NAMES: ApiAtlasV2AlertConfigsMatchersFieldNames,
        PathValues.API_ATLAS_V2_CLUSTERS: ApiAtlasV2Clusters,
        PathValues.API_ATLAS_V2_EXAMPLE_INFO: ApiAtlasV2ExampleInfo,
        PathValues.API_ATLAS_V2_FEDERATION_SETTINGS_FEDERATION_SETTINGS_ID: ApiAtlasV2FederationSettingsFederationSettingsId,
        PathValues.API_ATLAS_V2_FEDERATION_SETTINGS_FEDERATION_SETTINGS_ID_CONNECTED_ORG_CONFIGS: ApiAtlasV2FederationSettingsFederationSettingsIdConnectedOrgConfigs,
        PathValues.API_ATLAS_V2_FEDERATION_SETTINGS_FEDERATION_SETTINGS_ID_CONNECTED_ORG_CONFIGS_ORG_ID: ApiAtlasV2FederationSettingsFederationSettingsIdConnectedOrgConfigsOrgId,
        PathValues.API_ATLAS_V2_FEDERATION_SETTINGS_FEDERATION_SETTINGS_ID_CONNECTED_ORG_CONFIGS_ORG_ID_ROLE_MAPPINGS: ApiAtlasV2FederationSettingsFederationSettingsIdConnectedOrgConfigsOrgIdRoleMappings,
        PathValues.API_ATLAS_V2_FEDERATION_SETTINGS_FEDERATION_SETTINGS_ID_CONNECTED_ORG_CONFIGS_ORG_ID_ROLE_MAPPINGS_ID: ApiAtlasV2FederationSettingsFederationSettingsIdConnectedOrgConfigsOrgIdRoleMappingsId,
        PathValues.API_ATLAS_V2_FEDERATION_SETTINGS_FEDERATION_SETTINGS_ID_IDENTITY_PROVIDERS: ApiAtlasV2FederationSettingsFederationSettingsIdIdentityProviders,
        PathValues.API_ATLAS_V2_FEDERATION_SETTINGS_FEDERATION_SETTINGS_ID_IDENTITY_PROVIDERS_IDENTITY_PROVIDER_ID: ApiAtlasV2FederationSettingsFederationSettingsIdIdentityProvidersIdentityProviderId,
        PathValues.API_ATLAS_V2_FEDERATION_SETTINGS_FEDERATION_SETTINGS_ID_IDENTITY_PROVIDERS_IDENTITY_PROVIDER_ID_METADATA_XML: ApiAtlasV2FederationSettingsFederationSettingsIdIdentityProvidersIdentityProviderIdMetadataXml,
        PathValues.API_ATLAS_V2_GROUPS: ApiAtlasV2Groups,
        PathValues.API_ATLAS_V2_GROUPS_BY_NAME_GROUP_NAME: ApiAtlasV2GroupsByNameGroupName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID: ApiAtlasV2GroupsGroupId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_ACCESS_LIST: ApiAtlasV2GroupsGroupIdAccessList,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_ACCESS_LIST_ENTRY_VALUE: ApiAtlasV2GroupsGroupIdAccessListEntryValue,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_ACCESS_LIST_ENTRY_VALUE_STATUS: ApiAtlasV2GroupsGroupIdAccessListEntryValueStatus,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_ALERT_CONFIGS: ApiAtlasV2GroupsGroupIdAlertConfigs,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_ALERT_CONFIGS_ALERT_CONFIG_ID: ApiAtlasV2GroupsGroupIdAlertConfigsAlertConfigId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_ALERT_CONFIGS_ALERT_CONFIG_ID_ALERTS: ApiAtlasV2GroupsGroupIdAlertConfigsAlertConfigIdAlerts,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_ALERTS: ApiAtlasV2GroupsGroupIdAlerts,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_ALERTS_ALERT_ID: ApiAtlasV2GroupsGroupIdAlertsAlertId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_ALERTS_ALERT_ID_ALERT_CONFIGS: ApiAtlasV2GroupsGroupIdAlertsAlertIdAlertConfigs,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_API_KEYS: ApiAtlasV2GroupsGroupIdApiKeys,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_API_KEYS_API_USER_ID: ApiAtlasV2GroupsGroupIdApiKeysApiUserId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_AUDIT_LOG: ApiAtlasV2GroupsGroupIdAuditLog,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_AWS_CUSTOM_DNS: ApiAtlasV2GroupsGroupIdAwsCustomDNS,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_BACKUP_EXPORT_BUCKETS: ApiAtlasV2GroupsGroupIdBackupExportBuckets,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_BACKUP_EXPORT_BUCKETS_EXPORT_BUCKET_ID: ApiAtlasV2GroupsGroupIdBackupExportBucketsExportBucketId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLOUD_PROVIDER_ACCESS: ApiAtlasV2GroupsGroupIdCloudProviderAccess,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLOUD_PROVIDER_ACCESS_CLOUD_PROVIDER_ROLE_ID: ApiAtlasV2GroupsGroupIdCloudProviderAccessCloudProviderRoleId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLOUD_PROVIDER_ACCESS_ROLE_ID: ApiAtlasV2GroupsGroupIdCloudProviderAccessRoleId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS: ApiAtlasV2GroupsGroupIdClusters,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_PROVIDER_REGIONS: ApiAtlasV2GroupsGroupIdClustersProviderRegions,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_TENANT_UPGRADE: ApiAtlasV2GroupsGroupIdClustersTenantUpgrade,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_TENANT_UPGRADE_TO_SERVERLESS: ApiAtlasV2GroupsGroupIdClustersTenantUpgradeToServerless,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME: ApiAtlasV2GroupsGroupIdClustersClusterName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_EXPORTS: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupExports,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_EXPORTS_EXPORT_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupExportsExportId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_RESTORE_JOBS: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupRestoreJobs,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_RESTORE_JOBS_RESTORE_JOB_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupRestoreJobsRestoreJobId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_SCHEDULE: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupSchedule,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_SNAPSHOTS: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupSnapshots,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_SNAPSHOTS_SHARDED_CLUSTER_SNAPSHOT_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupSnapshotsShardedClusterSnapshotId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_SNAPSHOTS_SHARDED_CLUSTERS: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupSnapshotsShardedClusters,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_SNAPSHOTS_SNAPSHOT_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupSnapshotsSnapshotId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_TENANT_DOWNLOAD: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupTenantDownload,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_TENANT_RESTORE: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupTenantRestore,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_TENANT_RESTORES: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupTenantRestores,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_TENANT_RESTORES_RESTORE_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupTenantRestoresRestoreId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_TENANT_SNAPSHOTS: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupTenantSnapshots,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_TENANT_SNAPSHOTS_SNAPSHOT_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupTenantSnapshotsSnapshotId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_CHECKPOINTS: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupCheckpoints,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_CHECKPOINTS_CHECKPOINT_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupCheckpointsCheckpointId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_FTS_INDEXES: ApiAtlasV2GroupsGroupIdClustersClusterNameFtsIndexes,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_FTS_INDEXES_DATABASE_NAME_COLLECTION_NAME: ApiAtlasV2GroupsGroupIdClustersClusterNameFtsIndexesDatabaseNameCollectionName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_FTS_INDEXES_INDEX_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameFtsIndexesIndexId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_GLOBAL_WRITES: ApiAtlasV2GroupsGroupIdClustersClusterNameGlobalWrites,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_GLOBAL_WRITES_CUSTOM_ZONE_MAPPING: ApiAtlasV2GroupsGroupIdClustersClusterNameGlobalWritesCustomZoneMapping,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_GLOBAL_WRITES_MANAGED_NAMESPACES: ApiAtlasV2GroupsGroupIdClustersClusterNameGlobalWritesManagedNamespaces,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_INDEX: ApiAtlasV2GroupsGroupIdClustersClusterNameIndex,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_ONLINE_ARCHIVES: ApiAtlasV2GroupsGroupIdClustersClusterNameOnlineArchives,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_ONLINE_ARCHIVES_QUERY_LOGS_GZ: ApiAtlasV2GroupsGroupIdClustersClusterNameOnlineArchivesQueryLogsGz,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_ONLINE_ARCHIVES_ARCHIVE_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameOnlineArchivesArchiveId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_OUTAGE_SIMULATION: ApiAtlasV2GroupsGroupIdClustersClusterNameOutageSimulation,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_PROCESS_ARGS: ApiAtlasV2GroupsGroupIdClustersClusterNameProcessArgs,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_RESTART_PRIMARIES: ApiAtlasV2GroupsGroupIdClustersClusterNameRestartPrimaries,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_RESTORE_JOBS: ApiAtlasV2GroupsGroupIdClustersClusterNameRestoreJobs,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_RESTORE_JOBS_JOB_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameRestoreJobsJobId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_SNAPSHOT_SCHEDULE: ApiAtlasV2GroupsGroupIdClustersClusterNameSnapshotSchedule,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_SNAPSHOTS: ApiAtlasV2GroupsGroupIdClustersClusterNameSnapshots,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_SNAPSHOTS_SNAPSHOT_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameSnapshotsSnapshotId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_STATUS: ApiAtlasV2GroupsGroupIdClustersClusterNameStatus,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_HOST_NAME_LOGS_LOG_NAME_GZ: ApiAtlasV2GroupsGroupIdClustersHostNameLogsLogNameGz,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CONTAINERS: ApiAtlasV2GroupsGroupIdContainers,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CONTAINERS_ALL: ApiAtlasV2GroupsGroupIdContainersAll,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CONTAINERS_CONTAINER_ID: ApiAtlasV2GroupsGroupIdContainersContainerId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CUSTOM_DBROLES_ROLES: ApiAtlasV2GroupsGroupIdCustomDBRolesRoles,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CUSTOM_DBROLES_ROLES_ROLE_NAME: ApiAtlasV2GroupsGroupIdCustomDBRolesRolesRoleName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DATA_FEDERATION: ApiAtlasV2GroupsGroupIdDataFederation,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DATA_FEDERATION_TENANT_NAME: ApiAtlasV2GroupsGroupIdDataFederationTenantName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DATA_FEDERATION_TENANT_NAME_LIMITS: ApiAtlasV2GroupsGroupIdDataFederationTenantNameLimits,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DATA_FEDERATION_TENANT_NAME_LIMITS_LIMIT_NAME: ApiAtlasV2GroupsGroupIdDataFederationTenantNameLimitsLimitName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DATA_FEDERATION_TENANT_NAME_QUERY_LOGS_GZ: ApiAtlasV2GroupsGroupIdDataFederationTenantNameQueryLogsGz,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DATA_PROTECTION: ApiAtlasV2GroupsGroupIdDataProtection,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DATABASE_USERS: ApiAtlasV2GroupsGroupIdDatabaseUsers,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DATABASE_USERS_DATABASE_NAME_USERNAME: ApiAtlasV2GroupsGroupIdDatabaseUsersDatabaseNameUsername,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DATABASE_USERS_USERNAME_CERTS: ApiAtlasV2GroupsGroupIdDatabaseUsersUsernameCerts,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DB_ACCESS_HISTORY_CLUSTERS_CLUSTER_NAME: ApiAtlasV2GroupsGroupIdDbAccessHistoryClustersClusterName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DB_ACCESS_HISTORY_PROCESSES_HOSTNAME: ApiAtlasV2GroupsGroupIdDbAccessHistoryProcessesHostname,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_ENCRYPTION_AT_REST: ApiAtlasV2GroupsGroupIdEncryptionAtRest,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_EVENTS: ApiAtlasV2GroupsGroupIdEvents,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_EVENTS_EVENT_ID: ApiAtlasV2GroupsGroupIdEventsEventId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_HOSTS_PROCESS_ID_FTS_METRICS: ApiAtlasV2GroupsGroupIdHostsProcessIdFtsMetrics,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_HOSTS_PROCESS_ID_FTS_METRICS_INDEXES_DATABASE_NAME_COLLECTION_NAME_MEASUREMENTS: ApiAtlasV2GroupsGroupIdHostsProcessIdFtsMetricsIndexesDatabaseNameCollectionNameMeasurements,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_HOSTS_PROCESS_ID_FTS_METRICS_INDEXES_DATABASE_NAME_COLLECTION_NAME_INDEX_NAME_MEASUREMENTS: ApiAtlasV2GroupsGroupIdHostsProcessIdFtsMetricsIndexesDatabaseNameCollectionNameIndexNameMeasurements,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_HOSTS_PROCESS_ID_FTS_METRICS_MEASUREMENTS: ApiAtlasV2GroupsGroupIdHostsProcessIdFtsMetricsMeasurements,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_INTEGRATIONS: ApiAtlasV2GroupsGroupIdIntegrations,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_INTEGRATIONS_INTEGRATION_TYPE: ApiAtlasV2GroupsGroupIdIntegrationsIntegrationType,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_INVITES: ApiAtlasV2GroupsGroupIdInvites,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_INVITES_INVITATION_ID: ApiAtlasV2GroupsGroupIdInvitesInvitationId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_LIMITS: ApiAtlasV2GroupsGroupIdLimits,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_LIMITS_LIMIT_NAME: ApiAtlasV2GroupsGroupIdLimitsLimitName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_LIVE_MIGRATIONS: ApiAtlasV2GroupsGroupIdLiveMigrations,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_LIVE_MIGRATIONS_VALIDATE: ApiAtlasV2GroupsGroupIdLiveMigrationsValidate,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_LIVE_MIGRATIONS_VALIDATE_VALIDATION_ID: ApiAtlasV2GroupsGroupIdLiveMigrationsValidateValidationId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_LIVE_MIGRATIONS_LIVE_MIGRATION_ID: ApiAtlasV2GroupsGroupIdLiveMigrationsLiveMigrationId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_LIVE_MIGRATIONS_LIVE_MIGRATION_ID_CUTOVER: ApiAtlasV2GroupsGroupIdLiveMigrationsLiveMigrationIdCutover,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_MAINTENANCE_WINDOW: ApiAtlasV2GroupsGroupIdMaintenanceWindow,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_MAINTENANCE_WINDOW_AUTO_DEFER: ApiAtlasV2GroupsGroupIdMaintenanceWindowAutoDefer,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_MAINTENANCE_WINDOW_DEFER: ApiAtlasV2GroupsGroupIdMaintenanceWindowDefer,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_MANAGED_SLOW_MS_DISABLE: ApiAtlasV2GroupsGroupIdManagedSlowMsDisable,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_MANAGED_SLOW_MS_ENABLE: ApiAtlasV2GroupsGroupIdManagedSlowMsEnable,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PEERS: ApiAtlasV2GroupsGroupIdPeers,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PEERS_PEER_ID: ApiAtlasV2GroupsGroupIdPeersPeerId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PIPELINES: ApiAtlasV2GroupsGroupIdPipelines,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PIPELINES_PIPELINE_NAME: ApiAtlasV2GroupsGroupIdPipelinesPipelineName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PIPELINES_PIPELINE_NAME_AVAILABLE_SCHEDULES: ApiAtlasV2GroupsGroupIdPipelinesPipelineNameAvailableSchedules,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PIPELINES_PIPELINE_NAME_AVAILABLE_SNAPSHOTS: ApiAtlasV2GroupsGroupIdPipelinesPipelineNameAvailableSnapshots,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PIPELINES_PIPELINE_NAME_PAUSE: ApiAtlasV2GroupsGroupIdPipelinesPipelineNamePause,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PIPELINES_PIPELINE_NAME_RESUME: ApiAtlasV2GroupsGroupIdPipelinesPipelineNameResume,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PIPELINES_PIPELINE_NAME_RUNS: ApiAtlasV2GroupsGroupIdPipelinesPipelineNameRuns,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PIPELINES_PIPELINE_NAME_RUNS_PIPELINE_RUN_ID: ApiAtlasV2GroupsGroupIdPipelinesPipelineNameRunsPipelineRunId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PIPELINES_PIPELINE_NAME_TRIGGER: ApiAtlasV2GroupsGroupIdPipelinesPipelineNameTrigger,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_ENDPOINT_ENDPOINT_SERVICE: ApiAtlasV2GroupsGroupIdPrivateEndpointEndpointService,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_ENDPOINT_REGIONAL_MODE: ApiAtlasV2GroupsGroupIdPrivateEndpointRegionalMode,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_ENDPOINT_SERVERLESS_INSTANCE_INSTANCE_NAME_ENDPOINT: ApiAtlasV2GroupsGroupIdPrivateEndpointServerlessInstanceInstanceNameEndpoint,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_ENDPOINT_SERVERLESS_INSTANCE_INSTANCE_NAME_ENDPOINT_ENDPOINT_ID: ApiAtlasV2GroupsGroupIdPrivateEndpointServerlessInstanceInstanceNameEndpointEndpointId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_ENDPOINT_CLOUD_PROVIDER_ENDPOINT_SERVICE: ApiAtlasV2GroupsGroupIdPrivateEndpointCloudProviderEndpointService,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_ENDPOINT_CLOUD_PROVIDER_ENDPOINT_SERVICE_ENDPOINT_SERVICE_ID: ApiAtlasV2GroupsGroupIdPrivateEndpointCloudProviderEndpointServiceEndpointServiceId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_ENDPOINT_CLOUD_PROVIDER_ENDPOINT_SERVICE_ENDPOINT_SERVICE_ID_ENDPOINT: ApiAtlasV2GroupsGroupIdPrivateEndpointCloudProviderEndpointServiceEndpointServiceIdEndpoint,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_ENDPOINT_CLOUD_PROVIDER_ENDPOINT_SERVICE_ENDPOINT_SERVICE_ID_ENDPOINT_ENDPOINT_ID: ApiAtlasV2GroupsGroupIdPrivateEndpointCloudProviderEndpointServiceEndpointServiceIdEndpointEndpointId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_IP_MODE: ApiAtlasV2GroupsGroupIdPrivateIpMode,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_NETWORK_SETTINGS_ENDPOINT_IDS: ApiAtlasV2GroupsGroupIdPrivateNetworkSettingsEndpointIds,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_NETWORK_SETTINGS_ENDPOINT_IDS_ENDPOINT_ID: ApiAtlasV2GroupsGroupIdPrivateNetworkSettingsEndpointIdsEndpointId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES: ApiAtlasV2GroupsGroupIdProcesses,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID: ApiAtlasV2GroupsGroupIdProcessesProcessId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID_DATABASES: ApiAtlasV2GroupsGroupIdProcessesProcessIdDatabases,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID_DATABASES_DATABASE_NAME: ApiAtlasV2GroupsGroupIdProcessesProcessIdDatabasesDatabaseName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID_DATABASES_DATABASE_NAME_MEASUREMENTS: ApiAtlasV2GroupsGroupIdProcessesProcessIdDatabasesDatabaseNameMeasurements,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID_DISKS: ApiAtlasV2GroupsGroupIdProcessesProcessIdDisks,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID_DISKS_PARTITION_NAME: ApiAtlasV2GroupsGroupIdProcessesProcessIdDisksPartitionName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID_DISKS_PARTITION_NAME_MEASUREMENTS: ApiAtlasV2GroupsGroupIdProcessesProcessIdDisksPartitionNameMeasurements,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID_MEASUREMENTS: ApiAtlasV2GroupsGroupIdProcessesProcessIdMeasurements,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID_PERFORMANCE_ADVISOR_NAMESPACES: ApiAtlasV2GroupsGroupIdProcessesProcessIdPerformanceAdvisorNamespaces,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID_PERFORMANCE_ADVISOR_SLOW_QUERY_LOGS: ApiAtlasV2GroupsGroupIdProcessesProcessIdPerformanceAdvisorSlowQueryLogs,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID_PERFORMANCE_ADVISOR_SUGGESTED_INDEXES: ApiAtlasV2GroupsGroupIdProcessesProcessIdPerformanceAdvisorSuggestedIndexes,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_SAMPLE_DATASET_LOAD_NAME: ApiAtlasV2GroupsGroupIdSampleDatasetLoadName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_SAMPLE_DATASET_LOAD_SAMPLE_DATASET_ID: ApiAtlasV2GroupsGroupIdSampleDatasetLoadSampleDatasetId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_SERVERLESS: ApiAtlasV2GroupsGroupIdServerless,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_SERVERLESS_CLUSTER_NAME_BACKUP_RESTORE_JOBS: ApiAtlasV2GroupsGroupIdServerlessClusterNameBackupRestoreJobs,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_SERVERLESS_CLUSTER_NAME_BACKUP_RESTORE_JOBS_RESTORE_JOB_ID: ApiAtlasV2GroupsGroupIdServerlessClusterNameBackupRestoreJobsRestoreJobId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_SERVERLESS_CLUSTER_NAME_BACKUP_SNAPSHOTS: ApiAtlasV2GroupsGroupIdServerlessClusterNameBackupSnapshots,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_SERVERLESS_CLUSTER_NAME_BACKUP_SNAPSHOTS_SNAPSHOT_ID: ApiAtlasV2GroupsGroupIdServerlessClusterNameBackupSnapshotsSnapshotId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_SERVERLESS_NAME: ApiAtlasV2GroupsGroupIdServerlessName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_SETTINGS: ApiAtlasV2GroupsGroupIdSettings,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_TEAMS: ApiAtlasV2GroupsGroupIdTeams,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_TEAMS_TEAM_ID: ApiAtlasV2GroupsGroupIdTeamsTeamId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_USER_SECURITY: ApiAtlasV2GroupsGroupIdUserSecurity,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_USER_SECURITY_CUSTOMER_X509: ApiAtlasV2GroupsGroupIdUserSecurityCustomerX509,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_USER_SECURITY_LDAP_USER_TO_DNMAPPING: ApiAtlasV2GroupsGroupIdUserSecurityLdapUserToDNMapping,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_USER_SECURITY_LDAP_VERIFY: ApiAtlasV2GroupsGroupIdUserSecurityLdapVerify,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_USER_SECURITY_LDAP_VERIFY_REQUEST_ID: ApiAtlasV2GroupsGroupIdUserSecurityLdapVerifyRequestId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_USERS: ApiAtlasV2GroupsGroupIdUsers,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_USERS_USER_ID: ApiAtlasV2GroupsGroupIdUsersUserId,
        PathValues.API_ATLAS_V2_ORGS: ApiAtlasV2Orgs,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID: ApiAtlasV2OrgsOrgId,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_API_KEYS: ApiAtlasV2OrgsOrgIdApiKeys,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_API_KEYS_API_USER_ID: ApiAtlasV2OrgsOrgIdApiKeysApiUserId,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_API_KEYS_API_USER_ID_ACCESS_LIST: ApiAtlasV2OrgsOrgIdApiKeysApiUserIdAccessList,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_API_KEYS_API_USER_ID_ACCESS_LIST_IP_ADDRESS: ApiAtlasV2OrgsOrgIdApiKeysApiUserIdAccessListIpAddress,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_EVENTS: ApiAtlasV2OrgsOrgIdEvents,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_EVENTS_EVENT_ID: ApiAtlasV2OrgsOrgIdEventsEventId,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_FEDERATION_SETTINGS: ApiAtlasV2OrgsOrgIdFederationSettings,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_GROUPS: ApiAtlasV2OrgsOrgIdGroups,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_INVITES: ApiAtlasV2OrgsOrgIdInvites,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_INVITES_INVITATION_ID: ApiAtlasV2OrgsOrgIdInvitesInvitationId,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_INVOICES: ApiAtlasV2OrgsOrgIdInvoices,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_INVOICES_PENDING: ApiAtlasV2OrgsOrgIdInvoicesPending,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_INVOICES_INVOICE_ID: ApiAtlasV2OrgsOrgIdInvoicesInvoiceId,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_INVOICES_INVOICE_ID_CSV: ApiAtlasV2OrgsOrgIdInvoicesInvoiceIdCsv,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_LIVE_MIGRATIONS_AVAILABLE_PROJECTS: ApiAtlasV2OrgsOrgIdLiveMigrationsAvailableProjects,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_LIVE_MIGRATIONS_LINK_TOKENS: ApiAtlasV2OrgsOrgIdLiveMigrationsLinkTokens,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_SETTINGS: ApiAtlasV2OrgsOrgIdSettings,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_TEAMS: ApiAtlasV2OrgsOrgIdTeams,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_TEAMS_BY_NAME_TEAM_NAME: ApiAtlasV2OrgsOrgIdTeamsByNameTeamName,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_TEAMS_TEAM_ID: ApiAtlasV2OrgsOrgIdTeamsTeamId,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_TEAMS_TEAM_ID_USERS: ApiAtlasV2OrgsOrgIdTeamsTeamIdUsers,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_TEAMS_TEAM_ID_USERS_USER_ID: ApiAtlasV2OrgsOrgIdTeamsTeamIdUsersUserId,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_USERS: ApiAtlasV2OrgsOrgIdUsers,
        PathValues.API_ATLAS_V2_USERS: ApiAtlasV2Users,
        PathValues.API_ATLAS_V2_USERS_BY_NAME_USER_NAME: ApiAtlasV2UsersByNameUserName,
        PathValues.API_ATLAS_V2_USERS_USER_ID: ApiAtlasV2UsersUserId,
    }
)

path_to_api = PathToApi(
    {
        PathValues.API_ATLAS_V2: ApiAtlasV2,
        PathValues.API_ATLAS_V2_ALERT_CONFIGS_MATCHERS_FIELD_NAMES: ApiAtlasV2AlertConfigsMatchersFieldNames,
        PathValues.API_ATLAS_V2_CLUSTERS: ApiAtlasV2Clusters,
        PathValues.API_ATLAS_V2_EXAMPLE_INFO: ApiAtlasV2ExampleInfo,
        PathValues.API_ATLAS_V2_FEDERATION_SETTINGS_FEDERATION_SETTINGS_ID: ApiAtlasV2FederationSettingsFederationSettingsId,
        PathValues.API_ATLAS_V2_FEDERATION_SETTINGS_FEDERATION_SETTINGS_ID_CONNECTED_ORG_CONFIGS: ApiAtlasV2FederationSettingsFederationSettingsIdConnectedOrgConfigs,
        PathValues.API_ATLAS_V2_FEDERATION_SETTINGS_FEDERATION_SETTINGS_ID_CONNECTED_ORG_CONFIGS_ORG_ID: ApiAtlasV2FederationSettingsFederationSettingsIdConnectedOrgConfigsOrgId,
        PathValues.API_ATLAS_V2_FEDERATION_SETTINGS_FEDERATION_SETTINGS_ID_CONNECTED_ORG_CONFIGS_ORG_ID_ROLE_MAPPINGS: ApiAtlasV2FederationSettingsFederationSettingsIdConnectedOrgConfigsOrgIdRoleMappings,
        PathValues.API_ATLAS_V2_FEDERATION_SETTINGS_FEDERATION_SETTINGS_ID_CONNECTED_ORG_CONFIGS_ORG_ID_ROLE_MAPPINGS_ID: ApiAtlasV2FederationSettingsFederationSettingsIdConnectedOrgConfigsOrgIdRoleMappingsId,
        PathValues.API_ATLAS_V2_FEDERATION_SETTINGS_FEDERATION_SETTINGS_ID_IDENTITY_PROVIDERS: ApiAtlasV2FederationSettingsFederationSettingsIdIdentityProviders,
        PathValues.API_ATLAS_V2_FEDERATION_SETTINGS_FEDERATION_SETTINGS_ID_IDENTITY_PROVIDERS_IDENTITY_PROVIDER_ID: ApiAtlasV2FederationSettingsFederationSettingsIdIdentityProvidersIdentityProviderId,
        PathValues.API_ATLAS_V2_FEDERATION_SETTINGS_FEDERATION_SETTINGS_ID_IDENTITY_PROVIDERS_IDENTITY_PROVIDER_ID_METADATA_XML: ApiAtlasV2FederationSettingsFederationSettingsIdIdentityProvidersIdentityProviderIdMetadataXml,
        PathValues.API_ATLAS_V2_GROUPS: ApiAtlasV2Groups,
        PathValues.API_ATLAS_V2_GROUPS_BY_NAME_GROUP_NAME: ApiAtlasV2GroupsByNameGroupName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID: ApiAtlasV2GroupsGroupId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_ACCESS_LIST: ApiAtlasV2GroupsGroupIdAccessList,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_ACCESS_LIST_ENTRY_VALUE: ApiAtlasV2GroupsGroupIdAccessListEntryValue,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_ACCESS_LIST_ENTRY_VALUE_STATUS: ApiAtlasV2GroupsGroupIdAccessListEntryValueStatus,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_ALERT_CONFIGS: ApiAtlasV2GroupsGroupIdAlertConfigs,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_ALERT_CONFIGS_ALERT_CONFIG_ID: ApiAtlasV2GroupsGroupIdAlertConfigsAlertConfigId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_ALERT_CONFIGS_ALERT_CONFIG_ID_ALERTS: ApiAtlasV2GroupsGroupIdAlertConfigsAlertConfigIdAlerts,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_ALERTS: ApiAtlasV2GroupsGroupIdAlerts,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_ALERTS_ALERT_ID: ApiAtlasV2GroupsGroupIdAlertsAlertId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_ALERTS_ALERT_ID_ALERT_CONFIGS: ApiAtlasV2GroupsGroupIdAlertsAlertIdAlertConfigs,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_API_KEYS: ApiAtlasV2GroupsGroupIdApiKeys,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_API_KEYS_API_USER_ID: ApiAtlasV2GroupsGroupIdApiKeysApiUserId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_AUDIT_LOG: ApiAtlasV2GroupsGroupIdAuditLog,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_AWS_CUSTOM_DNS: ApiAtlasV2GroupsGroupIdAwsCustomDNS,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_BACKUP_EXPORT_BUCKETS: ApiAtlasV2GroupsGroupIdBackupExportBuckets,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_BACKUP_EXPORT_BUCKETS_EXPORT_BUCKET_ID: ApiAtlasV2GroupsGroupIdBackupExportBucketsExportBucketId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLOUD_PROVIDER_ACCESS: ApiAtlasV2GroupsGroupIdCloudProviderAccess,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLOUD_PROVIDER_ACCESS_CLOUD_PROVIDER_ROLE_ID: ApiAtlasV2GroupsGroupIdCloudProviderAccessCloudProviderRoleId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLOUD_PROVIDER_ACCESS_ROLE_ID: ApiAtlasV2GroupsGroupIdCloudProviderAccessRoleId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS: ApiAtlasV2GroupsGroupIdClusters,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_PROVIDER_REGIONS: ApiAtlasV2GroupsGroupIdClustersProviderRegions,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_TENANT_UPGRADE: ApiAtlasV2GroupsGroupIdClustersTenantUpgrade,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_TENANT_UPGRADE_TO_SERVERLESS: ApiAtlasV2GroupsGroupIdClustersTenantUpgradeToServerless,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME: ApiAtlasV2GroupsGroupIdClustersClusterName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_EXPORTS: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupExports,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_EXPORTS_EXPORT_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupExportsExportId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_RESTORE_JOBS: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupRestoreJobs,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_RESTORE_JOBS_RESTORE_JOB_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupRestoreJobsRestoreJobId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_SCHEDULE: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupSchedule,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_SNAPSHOTS: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupSnapshots,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_SNAPSHOTS_SHARDED_CLUSTER_SNAPSHOT_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupSnapshotsShardedClusterSnapshotId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_SNAPSHOTS_SHARDED_CLUSTERS: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupSnapshotsShardedClusters,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_SNAPSHOTS_SNAPSHOT_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupSnapshotsSnapshotId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_TENANT_DOWNLOAD: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupTenantDownload,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_TENANT_RESTORE: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupTenantRestore,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_TENANT_RESTORES: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupTenantRestores,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_TENANT_RESTORES_RESTORE_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupTenantRestoresRestoreId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_TENANT_SNAPSHOTS: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupTenantSnapshots,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_TENANT_SNAPSHOTS_SNAPSHOT_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupTenantSnapshotsSnapshotId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_CHECKPOINTS: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupCheckpoints,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_BACKUP_CHECKPOINTS_CHECKPOINT_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameBackupCheckpointsCheckpointId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_FTS_INDEXES: ApiAtlasV2GroupsGroupIdClustersClusterNameFtsIndexes,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_FTS_INDEXES_DATABASE_NAME_COLLECTION_NAME: ApiAtlasV2GroupsGroupIdClustersClusterNameFtsIndexesDatabaseNameCollectionName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_FTS_INDEXES_INDEX_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameFtsIndexesIndexId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_GLOBAL_WRITES: ApiAtlasV2GroupsGroupIdClustersClusterNameGlobalWrites,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_GLOBAL_WRITES_CUSTOM_ZONE_MAPPING: ApiAtlasV2GroupsGroupIdClustersClusterNameGlobalWritesCustomZoneMapping,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_GLOBAL_WRITES_MANAGED_NAMESPACES: ApiAtlasV2GroupsGroupIdClustersClusterNameGlobalWritesManagedNamespaces,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_INDEX: ApiAtlasV2GroupsGroupIdClustersClusterNameIndex,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_ONLINE_ARCHIVES: ApiAtlasV2GroupsGroupIdClustersClusterNameOnlineArchives,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_ONLINE_ARCHIVES_QUERY_LOGS_GZ: ApiAtlasV2GroupsGroupIdClustersClusterNameOnlineArchivesQueryLogsGz,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_ONLINE_ARCHIVES_ARCHIVE_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameOnlineArchivesArchiveId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_OUTAGE_SIMULATION: ApiAtlasV2GroupsGroupIdClustersClusterNameOutageSimulation,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_PROCESS_ARGS: ApiAtlasV2GroupsGroupIdClustersClusterNameProcessArgs,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_RESTART_PRIMARIES: ApiAtlasV2GroupsGroupIdClustersClusterNameRestartPrimaries,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_RESTORE_JOBS: ApiAtlasV2GroupsGroupIdClustersClusterNameRestoreJobs,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_RESTORE_JOBS_JOB_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameRestoreJobsJobId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_SNAPSHOT_SCHEDULE: ApiAtlasV2GroupsGroupIdClustersClusterNameSnapshotSchedule,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_SNAPSHOTS: ApiAtlasV2GroupsGroupIdClustersClusterNameSnapshots,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_SNAPSHOTS_SNAPSHOT_ID: ApiAtlasV2GroupsGroupIdClustersClusterNameSnapshotsSnapshotId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_CLUSTER_NAME_STATUS: ApiAtlasV2GroupsGroupIdClustersClusterNameStatus,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CLUSTERS_HOST_NAME_LOGS_LOG_NAME_GZ: ApiAtlasV2GroupsGroupIdClustersHostNameLogsLogNameGz,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CONTAINERS: ApiAtlasV2GroupsGroupIdContainers,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CONTAINERS_ALL: ApiAtlasV2GroupsGroupIdContainersAll,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CONTAINERS_CONTAINER_ID: ApiAtlasV2GroupsGroupIdContainersContainerId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CUSTOM_DBROLES_ROLES: ApiAtlasV2GroupsGroupIdCustomDBRolesRoles,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_CUSTOM_DBROLES_ROLES_ROLE_NAME: ApiAtlasV2GroupsGroupIdCustomDBRolesRolesRoleName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DATA_FEDERATION: ApiAtlasV2GroupsGroupIdDataFederation,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DATA_FEDERATION_TENANT_NAME: ApiAtlasV2GroupsGroupIdDataFederationTenantName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DATA_FEDERATION_TENANT_NAME_LIMITS: ApiAtlasV2GroupsGroupIdDataFederationTenantNameLimits,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DATA_FEDERATION_TENANT_NAME_LIMITS_LIMIT_NAME: ApiAtlasV2GroupsGroupIdDataFederationTenantNameLimitsLimitName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DATA_FEDERATION_TENANT_NAME_QUERY_LOGS_GZ: ApiAtlasV2GroupsGroupIdDataFederationTenantNameQueryLogsGz,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DATA_PROTECTION: ApiAtlasV2GroupsGroupIdDataProtection,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DATABASE_USERS: ApiAtlasV2GroupsGroupIdDatabaseUsers,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DATABASE_USERS_DATABASE_NAME_USERNAME: ApiAtlasV2GroupsGroupIdDatabaseUsersDatabaseNameUsername,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DATABASE_USERS_USERNAME_CERTS: ApiAtlasV2GroupsGroupIdDatabaseUsersUsernameCerts,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DB_ACCESS_HISTORY_CLUSTERS_CLUSTER_NAME: ApiAtlasV2GroupsGroupIdDbAccessHistoryClustersClusterName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_DB_ACCESS_HISTORY_PROCESSES_HOSTNAME: ApiAtlasV2GroupsGroupIdDbAccessHistoryProcessesHostname,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_ENCRYPTION_AT_REST: ApiAtlasV2GroupsGroupIdEncryptionAtRest,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_EVENTS: ApiAtlasV2GroupsGroupIdEvents,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_EVENTS_EVENT_ID: ApiAtlasV2GroupsGroupIdEventsEventId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_HOSTS_PROCESS_ID_FTS_METRICS: ApiAtlasV2GroupsGroupIdHostsProcessIdFtsMetrics,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_HOSTS_PROCESS_ID_FTS_METRICS_INDEXES_DATABASE_NAME_COLLECTION_NAME_MEASUREMENTS: ApiAtlasV2GroupsGroupIdHostsProcessIdFtsMetricsIndexesDatabaseNameCollectionNameMeasurements,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_HOSTS_PROCESS_ID_FTS_METRICS_INDEXES_DATABASE_NAME_COLLECTION_NAME_INDEX_NAME_MEASUREMENTS: ApiAtlasV2GroupsGroupIdHostsProcessIdFtsMetricsIndexesDatabaseNameCollectionNameIndexNameMeasurements,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_HOSTS_PROCESS_ID_FTS_METRICS_MEASUREMENTS: ApiAtlasV2GroupsGroupIdHostsProcessIdFtsMetricsMeasurements,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_INTEGRATIONS: ApiAtlasV2GroupsGroupIdIntegrations,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_INTEGRATIONS_INTEGRATION_TYPE: ApiAtlasV2GroupsGroupIdIntegrationsIntegrationType,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_INVITES: ApiAtlasV2GroupsGroupIdInvites,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_INVITES_INVITATION_ID: ApiAtlasV2GroupsGroupIdInvitesInvitationId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_LIMITS: ApiAtlasV2GroupsGroupIdLimits,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_LIMITS_LIMIT_NAME: ApiAtlasV2GroupsGroupIdLimitsLimitName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_LIVE_MIGRATIONS: ApiAtlasV2GroupsGroupIdLiveMigrations,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_LIVE_MIGRATIONS_VALIDATE: ApiAtlasV2GroupsGroupIdLiveMigrationsValidate,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_LIVE_MIGRATIONS_VALIDATE_VALIDATION_ID: ApiAtlasV2GroupsGroupIdLiveMigrationsValidateValidationId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_LIVE_MIGRATIONS_LIVE_MIGRATION_ID: ApiAtlasV2GroupsGroupIdLiveMigrationsLiveMigrationId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_LIVE_MIGRATIONS_LIVE_MIGRATION_ID_CUTOVER: ApiAtlasV2GroupsGroupIdLiveMigrationsLiveMigrationIdCutover,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_MAINTENANCE_WINDOW: ApiAtlasV2GroupsGroupIdMaintenanceWindow,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_MAINTENANCE_WINDOW_AUTO_DEFER: ApiAtlasV2GroupsGroupIdMaintenanceWindowAutoDefer,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_MAINTENANCE_WINDOW_DEFER: ApiAtlasV2GroupsGroupIdMaintenanceWindowDefer,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_MANAGED_SLOW_MS_DISABLE: ApiAtlasV2GroupsGroupIdManagedSlowMsDisable,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_MANAGED_SLOW_MS_ENABLE: ApiAtlasV2GroupsGroupIdManagedSlowMsEnable,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PEERS: ApiAtlasV2GroupsGroupIdPeers,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PEERS_PEER_ID: ApiAtlasV2GroupsGroupIdPeersPeerId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PIPELINES: ApiAtlasV2GroupsGroupIdPipelines,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PIPELINES_PIPELINE_NAME: ApiAtlasV2GroupsGroupIdPipelinesPipelineName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PIPELINES_PIPELINE_NAME_AVAILABLE_SCHEDULES: ApiAtlasV2GroupsGroupIdPipelinesPipelineNameAvailableSchedules,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PIPELINES_PIPELINE_NAME_AVAILABLE_SNAPSHOTS: ApiAtlasV2GroupsGroupIdPipelinesPipelineNameAvailableSnapshots,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PIPELINES_PIPELINE_NAME_PAUSE: ApiAtlasV2GroupsGroupIdPipelinesPipelineNamePause,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PIPELINES_PIPELINE_NAME_RESUME: ApiAtlasV2GroupsGroupIdPipelinesPipelineNameResume,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PIPELINES_PIPELINE_NAME_RUNS: ApiAtlasV2GroupsGroupIdPipelinesPipelineNameRuns,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PIPELINES_PIPELINE_NAME_RUNS_PIPELINE_RUN_ID: ApiAtlasV2GroupsGroupIdPipelinesPipelineNameRunsPipelineRunId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PIPELINES_PIPELINE_NAME_TRIGGER: ApiAtlasV2GroupsGroupIdPipelinesPipelineNameTrigger,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_ENDPOINT_ENDPOINT_SERVICE: ApiAtlasV2GroupsGroupIdPrivateEndpointEndpointService,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_ENDPOINT_REGIONAL_MODE: ApiAtlasV2GroupsGroupIdPrivateEndpointRegionalMode,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_ENDPOINT_SERVERLESS_INSTANCE_INSTANCE_NAME_ENDPOINT: ApiAtlasV2GroupsGroupIdPrivateEndpointServerlessInstanceInstanceNameEndpoint,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_ENDPOINT_SERVERLESS_INSTANCE_INSTANCE_NAME_ENDPOINT_ENDPOINT_ID: ApiAtlasV2GroupsGroupIdPrivateEndpointServerlessInstanceInstanceNameEndpointEndpointId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_ENDPOINT_CLOUD_PROVIDER_ENDPOINT_SERVICE: ApiAtlasV2GroupsGroupIdPrivateEndpointCloudProviderEndpointService,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_ENDPOINT_CLOUD_PROVIDER_ENDPOINT_SERVICE_ENDPOINT_SERVICE_ID: ApiAtlasV2GroupsGroupIdPrivateEndpointCloudProviderEndpointServiceEndpointServiceId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_ENDPOINT_CLOUD_PROVIDER_ENDPOINT_SERVICE_ENDPOINT_SERVICE_ID_ENDPOINT: ApiAtlasV2GroupsGroupIdPrivateEndpointCloudProviderEndpointServiceEndpointServiceIdEndpoint,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_ENDPOINT_CLOUD_PROVIDER_ENDPOINT_SERVICE_ENDPOINT_SERVICE_ID_ENDPOINT_ENDPOINT_ID: ApiAtlasV2GroupsGroupIdPrivateEndpointCloudProviderEndpointServiceEndpointServiceIdEndpointEndpointId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_IP_MODE: ApiAtlasV2GroupsGroupIdPrivateIpMode,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_NETWORK_SETTINGS_ENDPOINT_IDS: ApiAtlasV2GroupsGroupIdPrivateNetworkSettingsEndpointIds,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PRIVATE_NETWORK_SETTINGS_ENDPOINT_IDS_ENDPOINT_ID: ApiAtlasV2GroupsGroupIdPrivateNetworkSettingsEndpointIdsEndpointId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES: ApiAtlasV2GroupsGroupIdProcesses,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID: ApiAtlasV2GroupsGroupIdProcessesProcessId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID_DATABASES: ApiAtlasV2GroupsGroupIdProcessesProcessIdDatabases,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID_DATABASES_DATABASE_NAME: ApiAtlasV2GroupsGroupIdProcessesProcessIdDatabasesDatabaseName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID_DATABASES_DATABASE_NAME_MEASUREMENTS: ApiAtlasV2GroupsGroupIdProcessesProcessIdDatabasesDatabaseNameMeasurements,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID_DISKS: ApiAtlasV2GroupsGroupIdProcessesProcessIdDisks,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID_DISKS_PARTITION_NAME: ApiAtlasV2GroupsGroupIdProcessesProcessIdDisksPartitionName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID_DISKS_PARTITION_NAME_MEASUREMENTS: ApiAtlasV2GroupsGroupIdProcessesProcessIdDisksPartitionNameMeasurements,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID_MEASUREMENTS: ApiAtlasV2GroupsGroupIdProcessesProcessIdMeasurements,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID_PERFORMANCE_ADVISOR_NAMESPACES: ApiAtlasV2GroupsGroupIdProcessesProcessIdPerformanceAdvisorNamespaces,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID_PERFORMANCE_ADVISOR_SLOW_QUERY_LOGS: ApiAtlasV2GroupsGroupIdProcessesProcessIdPerformanceAdvisorSlowQueryLogs,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_PROCESSES_PROCESS_ID_PERFORMANCE_ADVISOR_SUGGESTED_INDEXES: ApiAtlasV2GroupsGroupIdProcessesProcessIdPerformanceAdvisorSuggestedIndexes,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_SAMPLE_DATASET_LOAD_NAME: ApiAtlasV2GroupsGroupIdSampleDatasetLoadName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_SAMPLE_DATASET_LOAD_SAMPLE_DATASET_ID: ApiAtlasV2GroupsGroupIdSampleDatasetLoadSampleDatasetId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_SERVERLESS: ApiAtlasV2GroupsGroupIdServerless,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_SERVERLESS_CLUSTER_NAME_BACKUP_RESTORE_JOBS: ApiAtlasV2GroupsGroupIdServerlessClusterNameBackupRestoreJobs,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_SERVERLESS_CLUSTER_NAME_BACKUP_RESTORE_JOBS_RESTORE_JOB_ID: ApiAtlasV2GroupsGroupIdServerlessClusterNameBackupRestoreJobsRestoreJobId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_SERVERLESS_CLUSTER_NAME_BACKUP_SNAPSHOTS: ApiAtlasV2GroupsGroupIdServerlessClusterNameBackupSnapshots,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_SERVERLESS_CLUSTER_NAME_BACKUP_SNAPSHOTS_SNAPSHOT_ID: ApiAtlasV2GroupsGroupIdServerlessClusterNameBackupSnapshotsSnapshotId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_SERVERLESS_NAME: ApiAtlasV2GroupsGroupIdServerlessName,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_SETTINGS: ApiAtlasV2GroupsGroupIdSettings,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_TEAMS: ApiAtlasV2GroupsGroupIdTeams,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_TEAMS_TEAM_ID: ApiAtlasV2GroupsGroupIdTeamsTeamId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_USER_SECURITY: ApiAtlasV2GroupsGroupIdUserSecurity,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_USER_SECURITY_CUSTOMER_X509: ApiAtlasV2GroupsGroupIdUserSecurityCustomerX509,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_USER_SECURITY_LDAP_USER_TO_DNMAPPING: ApiAtlasV2GroupsGroupIdUserSecurityLdapUserToDNMapping,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_USER_SECURITY_LDAP_VERIFY: ApiAtlasV2GroupsGroupIdUserSecurityLdapVerify,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_USER_SECURITY_LDAP_VERIFY_REQUEST_ID: ApiAtlasV2GroupsGroupIdUserSecurityLdapVerifyRequestId,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_USERS: ApiAtlasV2GroupsGroupIdUsers,
        PathValues.API_ATLAS_V2_GROUPS_GROUP_ID_USERS_USER_ID: ApiAtlasV2GroupsGroupIdUsersUserId,
        PathValues.API_ATLAS_V2_ORGS: ApiAtlasV2Orgs,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID: ApiAtlasV2OrgsOrgId,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_API_KEYS: ApiAtlasV2OrgsOrgIdApiKeys,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_API_KEYS_API_USER_ID: ApiAtlasV2OrgsOrgIdApiKeysApiUserId,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_API_KEYS_API_USER_ID_ACCESS_LIST: ApiAtlasV2OrgsOrgIdApiKeysApiUserIdAccessList,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_API_KEYS_API_USER_ID_ACCESS_LIST_IP_ADDRESS: ApiAtlasV2OrgsOrgIdApiKeysApiUserIdAccessListIpAddress,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_EVENTS: ApiAtlasV2OrgsOrgIdEvents,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_EVENTS_EVENT_ID: ApiAtlasV2OrgsOrgIdEventsEventId,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_FEDERATION_SETTINGS: ApiAtlasV2OrgsOrgIdFederationSettings,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_GROUPS: ApiAtlasV2OrgsOrgIdGroups,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_INVITES: ApiAtlasV2OrgsOrgIdInvites,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_INVITES_INVITATION_ID: ApiAtlasV2OrgsOrgIdInvitesInvitationId,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_INVOICES: ApiAtlasV2OrgsOrgIdInvoices,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_INVOICES_PENDING: ApiAtlasV2OrgsOrgIdInvoicesPending,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_INVOICES_INVOICE_ID: ApiAtlasV2OrgsOrgIdInvoicesInvoiceId,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_INVOICES_INVOICE_ID_CSV: ApiAtlasV2OrgsOrgIdInvoicesInvoiceIdCsv,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_LIVE_MIGRATIONS_AVAILABLE_PROJECTS: ApiAtlasV2OrgsOrgIdLiveMigrationsAvailableProjects,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_LIVE_MIGRATIONS_LINK_TOKENS: ApiAtlasV2OrgsOrgIdLiveMigrationsLinkTokens,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_SETTINGS: ApiAtlasV2OrgsOrgIdSettings,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_TEAMS: ApiAtlasV2OrgsOrgIdTeams,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_TEAMS_BY_NAME_TEAM_NAME: ApiAtlasV2OrgsOrgIdTeamsByNameTeamName,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_TEAMS_TEAM_ID: ApiAtlasV2OrgsOrgIdTeamsTeamId,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_TEAMS_TEAM_ID_USERS: ApiAtlasV2OrgsOrgIdTeamsTeamIdUsers,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_TEAMS_TEAM_ID_USERS_USER_ID: ApiAtlasV2OrgsOrgIdTeamsTeamIdUsersUserId,
        PathValues.API_ATLAS_V2_ORGS_ORG_ID_USERS: ApiAtlasV2OrgsOrgIdUsers,
        PathValues.API_ATLAS_V2_USERS: ApiAtlasV2Users,
        PathValues.API_ATLAS_V2_USERS_BY_NAME_USER_NAME: ApiAtlasV2UsersByNameUserName,
        PathValues.API_ATLAS_V2_USERS_USER_ID: ApiAtlasV2UsersUserId,
    }
)
