# coding: utf-8

"""
    MongoDB Atlas Administration API

    The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, constr, validator

class AzurePrivateEndpoint(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    delete_requested: Optional[StrictBool] = Field(None, alias="deleteRequested", description="Flag that indicates whether MongoDB Cloud received a request to remove the specified private endpoint from the private endpoint service.")
    error_message: Optional[StrictStr] = Field(None, alias="errorMessage", description="Error message returned when requesting private connection resource. The resource returns `null` if the request succeeded.")
    private_endpoint_connection_name: Optional[constr(strict=True)] = Field(None, alias="privateEndpointConnectionName", description="Human-readable label that MongoDB Cloud generates that identifies the private endpoint connection.")
    private_endpoint_ip_address: Optional[constr(strict=True)] = Field(None, alias="privateEndpointIPAddress", description="IPv4 address of the private endpoint in your Azure VNet that someone added to this private endpoint service.")
    private_endpoint_resource_id: Optional[StrictStr] = Field(None, alias="privateEndpointResourceId", description="Unique string that identifies the Azure private endpoint's network interface that someone added to this private endpoint service.")
    status: Optional[StrictStr] = Field(None, description="State of the Azure Private Link Service connection when MongoDB Cloud received this request.")
    __properties = ["deleteRequested", "errorMessage", "privateEndpointConnectionName", "privateEndpointIPAddress", "privateEndpointResourceId", "status"]

    @validator('private_endpoint_connection_name')
    def private_endpoint_connection_name_validate_regular_expression(cls, v):
        if not re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}%2[fF]([-\w._()]+)%2[fF]([-\w._()]+)", v):
            raise ValueError(r"must validate the regular expression /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}%2[fF]([-\w._()]+)%2[fF]([-\w._()]+)/")
        return v

    @validator('private_endpoint_ip_address')
    def private_endpoint_ip_address_validate_regular_expression(cls, v):
        if not re.match(r"^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)(\.(?!$)|$)){4}|([0-9a-f]{1,4}\:){7}[0-9a-f]{1,4}$", v):
            raise ValueError(r"must validate the regular expression /^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)(\.(?!$)|$)){4}|([0-9a-f]{1,4}\:){7}[0-9a-f]{1,4}$/")
        return v

    @validator('status')
    def status_validate_enum(cls, v):
        if v is None:
            return v

        if v not in ('INITIATING', 'AVAILABLE', 'FAILED', 'DELETING'):
            raise ValueError("must validate the enum values ('INITIATING', 'AVAILABLE', 'FAILED', 'DELETING')")
        return v

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AzurePrivateEndpoint:
        """Create an instance of AzurePrivateEndpoint from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "delete_requested",
                            "error_message",
                            "private_endpoint_connection_name",
                            "private_endpoint_resource_id",
                            "status",
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AzurePrivateEndpoint:
        """Create an instance of AzurePrivateEndpoint from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return AzurePrivateEndpoint.parse_obj(obj)

        _obj = AzurePrivateEndpoint.parse_obj({
            "delete_requested": obj.get("deleteRequested"),
            "error_message": obj.get("errorMessage"),
            "private_endpoint_connection_name": obj.get("privateEndpointConnectionName"),
            "private_endpoint_ip_address": obj.get("privateEndpointIPAddress"),
            "private_endpoint_resource_id": obj.get("privateEndpointResourceId"),
            "status": obj.get("status")
        })
        return _obj

