# coding: utf-8

"""
    MongoDB Atlas Administration API

    The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from inspect import getfullargspec
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class NDSServerlessInstanceAuditTypeView(str, Enum):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    allowed enum values
    """

    CREATED = 'SERVERLESS_INSTANCE_CREATED'
    READY = 'SERVERLESS_INSTANCE_READY'
    UPDATE_SUBMITTED = 'SERVERLESS_INSTANCE_UPDATE_SUBMITTED'
    UPDATE_STARTED = 'SERVERLESS_INSTANCE_UPDATE_STARTED'
    UPDATE_COMPLETED = 'SERVERLESS_INSTANCE_UPDATE_COMPLETED'
    DELETE_SUBMITTED = 'SERVERLESS_INSTANCE_DELETE_SUBMITTED'
    DELETED = 'SERVERLESS_INSTANCE_DELETED'

