# coding: utf-8

"""
    MongoDB Atlas Administration API

    The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt, constr

class PartitionField(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    field_name: constr(strict=True, max_length=700) = Field(..., alias="fieldName", description="Human-readable label that identifies the field name used to partition data.")
    order: StrictInt = Field(..., description="Sequence in which MongoDB Cloud slices the collection data to create partitions. The resource expresses this sequence starting with zero.")
    __properties = ["fieldName", "order"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PartitionField:
        """Create an instance of PartitionField from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PartitionField:
        """Create an instance of PartitionField from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return PartitionField.parse_obj(obj)

        _obj = PartitionField.parse_obj({
            "field_name": obj.get("fieldName"),
            "order": obj.get("order") if obj.get("order") is not None else 0
        })
        return _obj

