# coding: utf-8

"""
    MongoDB Atlas Administration API

    The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, validator

class TokenFilterdaitchMokotoffSoundex(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    original_tokens: Optional[StrictStr] = Field('include', alias="originalTokens", description="Value that indicates whether to include or omit the original tokens in the output of the token filter.  Choose `include` if you want to support queries on both the original tokens as well as the converted forms.   Choose `omit` if you want to query only on the converted forms of the original tokens.")
    type: StrictStr = Field(..., description="Human-readable label that identifies this token filter type.")
    __properties = ["originalTokens", "type"]

    @validator('original_tokens')
    def original_tokens_validate_enum(cls, v):
        if v is None:
            return v

        if v not in ('omit', 'include'):
            raise ValueError("must validate the enum values ('omit', 'include')")
        return v

    @validator('type')
    def type_validate_enum(cls, v):
        if v not in ('daitchMokotoffSoundex'):
            raise ValueError("must validate the enum values ('daitchMokotoffSoundex')")
        return v

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TokenFilterdaitchMokotoffSoundex:
        """Create an instance of TokenFilterdaitchMokotoffSoundex from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TokenFilterdaitchMokotoffSoundex:
        """Create an instance of TokenFilterdaitchMokotoffSoundex from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return TokenFilterdaitchMokotoffSoundex.parse_obj(obj)

        _obj = TokenFilterdaitchMokotoffSoundex.parse_obj({
            "original_tokens": obj.get("originalTokens") if obj.get("originalTokens") is not None else 'include',
            "type": obj.get("type")
        })
        return _obj

