# coding: utf-8

"""
    MongoDB Atlas Administration API

    The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""

from atlas.paths.api_atlas_v2_groups_group_id_user_security_ldap_user_to_dn_mapping.delete import DeleteLdapConfiguration
from atlas.paths.api_atlas_v2_groups_group_id_user_security.get import GetLdapConfiguration
from atlas.paths.api_atlas_v2_groups_group_id_user_security_ldap_verify_request_id.get import GetLdapConfigurationStatus
from atlas.paths.api_atlas_v2_groups_group_id_user_security.patch import SaveLdapConfiguration
from atlas.paths.api_atlas_v2_groups_group_id_user_security_ldap_verify.post import VerifyLdapConfiguration


class LDAPConfigurationApi(
    DeleteLdapConfiguration,
    GetLdapConfiguration,
    GetLdapConfigurationStatus,
    SaveLdapConfiguration,
    VerifyLdapConfiguration,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
