# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import atlas
from atlas.paths.api_atlas_v2_groups_group_id_hosts_process_id_fts_metrics_indexes_database_name_collection_name_index_name_measurements import get  # noqa: E501
from atlas import configuration, schemas, api_client

from .. import ApiTestMixin


class TestApiAtlasV2GroupsGroupIdHostsProcessIdFtsMetricsIndexesDatabaseNameCollectionNameIndexNameMeasurements(ApiTestMixin, unittest.TestCase):
    """
    ApiAtlasV2GroupsGroupIdHostsProcessIdFtsMetricsIndexesDatabaseNameCollectionNameIndexNameMeasurements unit test stubs
        Return Atlas Search Metrics for One Index in One Specified Namespace  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
